### ISSUE TITLE
add an option to directly seperate group chats and direct chats.

### ISSUE THREAD

**Issue by vachan-maker** [Nheko-Reborn/nheko#702] opened 2021-08-30 02:20 UTC
### The Problem

I am always frustrated when nheko combines the group chats and 1 to 1 chats.😀

### The Solution

An option in the settings to filter group chats and direct chats

### Alternatives

Using tags

### Additional context

Neochat and element has this option

### Happens in the latest version

- [x] Yes, this feature is still missing.

**Comment by deepbluev7** [comment] 2021-08-30 09:32
Duplicate of #296 #317

Please search the issue tracker before opening an issue .-.

**Closed by deepbluev7** 2021-08-30 09:32 UTC
Labels: enhancement
