### ISSUE TITLE
Dark theme issues

### ISSUE THREAD

**Issue by KAMiKAZOW** [Nheko-Reborn/nheko#118] opened 2020-02-15 17:58 UTC
### System:

- Nheko version: 0.6.4
- Installation method: https://build.opensuse.org/package/show/home:Dead_Mozay:matrix/nheko
- Operating System: Linux
- Qt version: 5.14.1
- C++ compiler: GCC 9
- Desktop Environment: Plasma 5.18.0

### Actual behavior
Colors of some tooltips and drop-down menus are wrong: light text on light background.

### Expected behavior
Light text on dark background

### Steps to reproduce
Enable dark theme

### Screenshots
![Screenshot_2020-02-15_18-51-34](https://user-images.githubusercontent.com/3259076/74592794-197f3300-5025-11ea-818f-b6e27fb71342.png)

![Screenshot_2020-02-15_18-52-03](https://user-images.githubusercontent.com/3259076/74592797-200daa80-5025-11ea-9c87-d585f15d4ab8.png)

**Comment by adasauce** [comment] 2020-02-15 21:42
I think this might have to do with your plasma theme.

here's what mine looks like in dark mode.

![image](https://user-images.githubusercontent.com/60991921/74595645-86410000-501a-11ea-8ab1-2d1009843929.png)

**Comment by deepbluev7** [comment] 2020-02-15 21:45
Well, the issue is, that the stylesheet for our dark mode isn't specifying colors for all elements, like dropdowns and tooltips. This should be easy enough to fix.

**Comment by adasauce** [comment] 2020-02-15 23:37
oh, so qt is inheriting the desktop theme for values that aren't set?

**Comment by KAMiKAZOW** [comment] 2020-02-16 08:35
My desktop theme is a light one because too many apps break with a global dark theme.

It seems that indeed some places inherit the lighter background from the desktop theme but apply their own text color to there.

**Comment by adasauce** [comment] 2020-02-20 19:09
Hey @KAMiKAZOW , quick question

do the tooltips over things like the file upload button, send message button, etc. in the main timeline view have correct styles for you?

**Comment by KAMiKAZOW** [comment] 2020-02-20 20:04
@adasauce Yes, those tooltips are fine.

**Comment by deepbluev7** [comment] 2020-02-20 20:05
Fixed. Thank you @adasauce for the work!

**Comment by AyushiG19** [comment] 2021-04-12 04:02
I want to fix this issue...please guide me as I am totally new to open source.

**Comment by deepbluev7** [comment] 2021-04-12 10:45
@AyushiG19  I would suggest joining #nheko:nheko.im and trying to build the app as a first step and we can go from there?

**Comment by deepbluev7** [comment] 2021-06-16 21:47
Tags are fixed now.

**Comment by deepbluev7** [comment] 2021-12-11 23:11
The only thing that is left imo is the settings page and that will be fixed by #647.

**Closed by deepbluev7** 2021-12-11 23:11 UTC
Labels: bug, good first issue
