### ISSUE TITLE
IOT instruction (core dumped) on startup in KDE on Arch Linux

### ISSUE THREAD

**Issue by n1trux** [Nheko-Reborn/nheko#1582] opened 2023-10-14 22:29 UTC
### Describe the bug

I get the following error on startup after unlocking the KDE Keyring on Arch Linux:

```
[2023-10-15 00:28:06.940] [ui] [info] Restoring window size 1027x1200
[2023-10-15 00:28:06.949] [ui] [info] WebRTC: initialised GStreamer 1.22.6
[2023-10-15 00:28:07.174] [ui] [info] jdenticon plugin not found.
[2023-10-15 00:28:07.248] [ui] [debug] CompletionProxyModel: build trie: 8.382588 ms
[2023-10-15 00:28:07.267] [ui] [info] starting nheko 0.11.3
[2023-10-15 00:28:07.269] [ui] [info] User already signed in, showing chat page
[2023-10-15 00:28:07.269] [db] [debug] setting up cache
[2023-10-15 00:28:07.269] [db] [debug] Reading 'pickle_secret'
[2023-10-15 00:28:07.269] [ui] [info] Switching to chat page
[2023-10-15 00:28:07.328] [ui] [debug] Filtering by thread ''
[2023-10-15 00:28:07.328] [ui] [debug] Filtering by content ''
[2023-10-15 00:28:07.329] [qml] [warning] qrc:/qml/TimelineView.qml:36:5: QML Shortcut: Shortcut: Only binding to one of multiple key bindings associated with 4. Use 'sequences: [ <key> ]' to bind to all of them. (qrc:/qml/TimelineView.qml:36, )
[2023-10-15 00:28:07.331] [ui] [debug] Profile requested
[2023-10-15 00:28:07.355] [qml] [warning] qrc:/qml/TopBar.qml:234:13: QML AbstractButton: Binding loop detected for property "implicitWidth" (qrc:/qml/TopBar.qml:234, )
[2023-10-15 00:28:07.355] [qml] [warning] qrc:/qml/TopBar.qml:241:30: QML EncryptionIndicator: Binding loop detected for property "sourceSize.height" (qrc:/qml/TopBar.qml:241, )
[2023-10-15 00:28:07.366] [ui] [info] Unity service available: true
[2023-10-15 00:28:07.369] [qml] [warning] qrc:/qml/ChatPage.qml:105:17: QML RoomList: Binding loop detected for property "implicitWidth" (qrc:/qml/ChatPage.qml:105, )
[2023-10-15 00:28:07.369] [qml] [warning] qrc:/qml/ChatPage.qml:105:17: QML RoomList: Binding loop detected for property "implicitWidth" (qrc:/qml/ChatPage.qml:105, )
[2023-10-15 00:28:07.398] [ui] [debug] WebRTC: audio device added: Monitor of HDA ATI HDMI Digital Stereo (HDMI)
[2023-10-15 00:28:07.400] [ui] [debug] Filtering by content ''
[2023-10-15 00:28:07.400] [ui] [debug] Filtering by thread ''
[2023-10-15 00:28:07.402] [ui] [debug] Profile requested
[2023-10-15 00:28:07.402] [ui] [debug] Filtering by thread ''
[2023-10-15 00:28:07.407] [ui] [debug] WebRTC: audio device added: Monitor of Family 17h/19h HD Audio Controller Analog Stereo
[2023-10-15 00:28:07.407] [ui] [debug] WebRTC: audio device added: Family 17h/19h HD Audio Controller Analog Stereo
[2023-10-15 00:28:07.408] [db] [debug] Finished reading 'pickle_secret'
[2023-10-15 00:28:07.408] [db] [info] database ready
[2023-10-15 00:28:07.408] [db] [info] restoring state from cache
[2023-10-15 00:28:07.425] [db] [info] Restored 459 rooms from cache
[2023-10-15 00:28:07.466] [db] [info] Invalidating self verification status
[2023-10-15 00:28:07.474] [crypto] [info] ed25519   : REDACTED
[2023-10-15 00:28:07.474] [crypto] [info] curve25519: REDACTED
[2023-10-15 00:28:07.495] [ui] [debug] Profile requested
[2023-10-15 00:28:07.495] [db] [debug] Marking user keys out of date: REDACTED
mdb.c:2156: Assertion 'rc == 0' failed in mdb_page_dirty()
Error: signal 6:
nheko(_Z17stacktraceHandleri+0x3f)[0x5599cb4698af]
/usr/lib/libc.so.6(+0x3e710)[0x7fe637c5c710]
/usr/lib/libc.so.6(+0x8e83c)[0x7fe637cac83c]
/usr/lib/libc.so.6(raise+0x18)[0x7fe637c5c668]
/usr/lib/libc.so.6(abort+0xd7)[0x7fe637c444b8]
/usr/lib/liblmdb.so(+0x591e)[0x7fe63a9bd91e]
/usr/lib/liblmdb.so(mdb_env_create+0x0)[0x7fe63a9bbc2a]
/usr/lib/liblmdb.so(+0x11646)[0x7fe63a9c9646]
/usr/lib/liblmdb.so(+0x8d53)[0x7fe63a9c0d53]
/usr/lib/liblmdb.so(+0x90a8)[0x7fe63a9c10a8]
/usr/lib/liblmdb.so(+0xa961)[0x7fe63a9c2961]
/usr/lib/liblmdb.so(mdb_cursor_put+0x4c0)[0x7fe63a9c54a0]
/usr/lib/liblmdb.so(mdb_put+0xf8)[0x7fe63a9c63c8]
nheko(+0x970b33)[0x5599cb48bb33]
nheko(_ZN5Cache21markUserKeysOutOfDateERN4lmdb3txnERNS0_3dbiERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISB_EERKSB_+0x4dd)[0x5599cb3da13d]
nheko(_ZN5Cache21markUserKeysOutOfDateERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS6_EE+0x98)[0x5599cb3da818]
nheko(+0x88edfe)[0x5599cb3a9dfe]
/usr/lib/libQt5Core.so.5(+0x2d04e7)[0x7fe6384d04e7]
nheko(_ZN8ChatPage18loadStateFromCacheEv+0x278)[0x5599cb405e28]
nheko(+0x8e5330)[0x5599cb400330]
/usr/lib/libQt5Core.so.5(+0x2d04e7)[0x7fe6384d04e7]
nheko(_ZN5Cache20loadSecretsFromStoreESt6vectorISt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbESaIS8_EESt8functionIFvRKS7_bSD_EEb+0x91f)[0x5599cb3b99ff]
nheko(+0x8e08ad)[0x5599cb3fb8ad]
/usr/lib/libQt5Core.so.5(_ZN7QObject5eventEP6QEvent+0x234)[0x7fe6384c3024]
/usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x8f)[0x7fe6391788ff]
/usr/lib/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x128)[0x7fe63849b5b8]
/usr/lib/libQt5Core.so.5(_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData+0x19b)[0x7fe6384a051b]
/usr/lib/libQt5Core.so.5(+0x2e6588)[0x7fe6384e6588]
/usr/lib/libglib-2.0.so.0(+0x59f19)[0x7fe63810df19]
/usr/lib/libglib-2.0.so.0(+0xb82b7)[0x7fe63816c2b7]
/usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x32)[0x7fe63810c112]
/usr/lib/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x6c)[0x7fe6384ea3cc]
/usr/lib/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x134)[0x7fe63849a2c4]
/usr/lib/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x93)[0x7fe63849b763]
nheko(main+0x1096)[0x5599cb1c5a76]
/usr/lib/libc.so.6(+0x27cd0)[0x7fe637c45cd0]
/usr/lib/libc.so.6(__libc_start_main+0x8a)[0x7fe637c45d8a]
nheko(_start+0x25)[0x5599cb1c8e65]
[1]    17200 IOT instruction (core dumped)  nheko
```

### To Reproduce

Happens on start for me. If I delete the profile, it works for a while and then it stops working again.

### Version

0.11.3-5

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.11+kde+r6-1

### Desktop Environment

KDE with kwin on Wayland / X11

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
cat nheko-crash.dump
Error: signal
nheko(_Z17stacktraceHandleri+0x3f)[0x5599cb4698af]
/usr/lib/libc.so.6(+0x3e710)[0x7fe637c5c710]
/usr/lib/libc.so.6(+0x8e83c)[0x7fe637cac83c]
/usr/lib/libc.so.6(raise+0x18)[0x7fe637c5c668]
/usr/lib/libc.so.6(abort+0xd7)[0x7fe637c444b8]
/usr/lib/liblmdb.so(+0x591e)[0x7fe63a9bd91e]
/usr/lib/liblmdb.so(mdb_env_create+0x0)[0x7fe63a9bbc2a]
/usr/lib/liblmdb.so(+0x11646)[0x7fe63a9c9646]
/usr/lib/liblmdb.so(+0x8d53)[0x7fe63a9c0d53]
/usr/lib/liblmdb.so(+0x90a8)[0x7fe63a9c10a8]
/usr/lib/liblmdb.so(+0xa961)[0x7fe63a9c2961]
/usr/lib/liblmdb.so(mdb_cursor_put+0x4c0)[0x7fe63a9c54a0]
/usr/lib/liblmdb.so(mdb_put+0xf8)[0x7fe63a9c63c8]
nheko(+0x970b33)[0x5599cb48bb33]
nheko(_ZN5Cache21markUserKeysOutOfDateERN4lmdb3txnERNS0_3dbiERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISB_EERKSB_+0x4dd)[0x5599cb3da13d]
nheko(_ZN5Cache21markUserKeysOutOfDateERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS6_EE+0x98)[0x5599cb3da818]
nheko(+0x88edfe)[0x5599cb3a9dfe]
/usr/lib/libQt5Core.so.5(+0x2d04e7)[0x7fe6384d04e7]
nheko(_ZN8ChatPage18loadStateFromCacheEv+0x278)[0x5599cb405e28]
nheko(+0x8e5330)[0x5599cb400330]
/usr/lib/libQt5Core.so.5(+0x2d04e7)[0x7fe6384d04e7]
nheko(_ZN5Cache20loadSecretsFromStoreESt6vectorISt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbESaIS8_EESt8functionIFvRKS7_bSD_EEb+0x91f)[0x5599cb3b99ff]
nheko(+0x8e08ad)[0x5599cb3fb8ad]
/usr/lib/libQt5Core.so.5(_ZN7QObject5eventEP6QEvent+0x234)[0x7fe6384c3024]
/usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x8f)[0x7fe6391788ff]
/usr/lib/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x128)[0x7fe63849b5b8]
/usr/lib/libQt5Core.so.5(_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData+0x19b)[0x7fe6384a051b]
/usr/lib/libQt5Core.so.5(+0x2e6588)[0x7fe6384e6588]
/usr/lib/libglib-2.0.so.0(+0x59f19)[0x7fe63810df19]
/usr/lib/libglib-2.0.so.0(+0xb82b7)[0x7fe63816c2b7]
/usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x32)[0x7fe63810c112]
/usr/lib/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x6c)[0x7fe6384ea3cc]
/usr/lib/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x134)[0x7fe63849a2c4]
/usr/lib/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x93)[0x7fe63849b763]
nheko(main+0x1096)[0x5599cb1c5a76]
/usr/lib/libc.so.6(+0x27cd0)[0x7fe637c45cd0]
/usr/lib/libc.so.6(__libc_start_main+0x8a)[0x7fe637c45d8a]
nheko(_start+0x25)[0x5599cb1c8e65]
```

**Comment by deepbluev7** [comment] 2023-10-21 18:05
Duplicate of #1303

**Closed by deepbluev7** 2023-10-21 18:05 UTC
Labels: bug
