### ISSUE TITLE
Messages with lists and `<ol>` starting at non-1 index are shown as starting at 1

### ISSUE THREAD

**Issue by rom4nik** [Nheko-Reborn/nheko#1579] opened 2023-10-09 22:20 UTC
### Describe the bug

See sections below, it seems like `start` parameter in `<ol>` is ignored during rendering of the messages.

Also, not sure if it's worth a separate issue, but if I send this with Nheko:
```
2. second
4. fourth
```
I get this in JSON:
```
    "content": {
        "body": "2. second\n4. fourth",
        "format": "org.matrix.custom.html",
        "formatted_body": "<ol start=\"2\">\n<li>second</li>\n<li>fourth</li>\n</ol>",
        "msgtype": "m.text"
    },
```
and it's rendered like this:
![obraz](https://github.com/Nheko-Reborn/nheko/assets/46846000/ee77dc59-1e6c-4fdb-84cf-33705ae9e379)

That's even more incorrect :/

### To Reproduce

1. Send the following message using Nheko: `2. second`
2. Ensure there's `<ol start=\"2\">` in `formatted_body`:
```
    "content": {
        "body": "2. second",
        "format": "org.matrix.custom.html",
        "formatted_body": "<ol start=\"2\">\n<li>second</li>\n</ol>",
        "msgtype": "m.text"
    },
```

### What happened?

Message is visible as a single-item list, starting at 1, with the following content visible: `1. second`

### Expected behavior

Message with `2. second` as visible content.

Overall I'm not sure if it should be treated as a list in that scenario, but that has been already reported in #1566.

### Screenshots

![obraz](https://github.com/Nheko-Reborn/nheko/assets/46846000/aceb5268-8e15-4f72-a16a-7927f340f39b)

### Version

0.11.3-5 (Arch package)

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

KDE with KWin, X11

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment] 2023-10-10 11:17
duplicate of #1566
duplicate of #793

Also already fixed in Qt6.6, so this will work once you have Qt6.6: https://codereview.qt-project.org/c/qt/qtbase/+/460444

**Closed by deepbluev7** 2023-10-10 11:17 UTC
Labels: bug
