### ISSUE TITLE
Nheko cannot paste some images from the clipboard

### ISSUE THREAD

**Issue by vachan-maker** [Nheko-Reborn/nheko#567] opened 2021-04-30 07:55 UTC
### Describe the bug
Nheko cannot paste some images from the clipboard. I take a lot of screenshots with a tool called [Greenshot] (https://getgreenshot.org). These images for some reason cannot be pasted into Nheko. 

Other application like LibreOffice, Element, etc is able to paste the image from the clipboard captured using Greenshot. The format of the image is png.

Operating System: Windows 10
Nheko version: 0.8.2-3dc1c3d7

**Comment by LorenDB** [comment] 2021-04-30 12:00
Duplicate of #399

**Closed** 2021-04-30 12:10 UTC
Labels: bug
