### ISSUE TITLE
Cannot invite users to new room

### ISSUE THREAD

**Issue by Peter2121** [Nheko-Reborn/nheko#37] opened 2019-02-27 20:28 UTC
- Nheko version: 0.6.3 Darwin
- Installation method: Built from sources
- Operating System: Mac OS X 10.13.6

### Actual behavior
No notification shown for the invited user.

### Expected behavior
User should receive a notification.

### Steps to reproduce
Create room, invite a user from the same domain. 

NOTE: User invited to direct chat correctly receives the invitation.

**Comment by vtronko** [comment] 2019-03-03 16:08
Can confirm.

**Comment by Peter2121** [comment] 2019-05-17 17:08
Any chance to get it fixed?

**Comment by deepbluev7** [comment] 2019-12-13 22:01
Can you verify, if that is still an issue? I fixed invites appearing at random positions for the invited user and the accept and decline button appearing at the wrong vertical position. So as long as the invite actually arrives, it should show for the user. You will need the 0.7.0-dev build though for testing!

**Comment by Peter2121** [comment] 2019-12-17 20:48
Just compiled  HEAD of 0.7.0-dev, hope to test it shortly.

**Comment by Peter2121** [comment] 2019-12-30 08:54
Tested on FreeBSD 11.3 - OK.
Hope to get access to Mac OS X shortly to test it there.

**Comment by deepbluev7** [comment] 2019-12-30 19:06
Thank you for testing this! I'll wait for your MacOS results, and then decide, if I will close this or hopefully figure out how to reproduce it.

**Comment by deepbluev7** [comment] 2020-02-23 13:14
Since this seems to work now, even though I didn't hear back about macOS, I will close this for now. If anyone can reproduce invites not working, please reopen.

**Closed by deepbluev7** 2020-02-23 13:14 UTC
