### ISSUE TITLE
Links are not tappable in touchscreen mode

### ISSUE THREAD

**Issue by SamuelNorbury** [Nheko-Reborn/nheko#748] opened 2021-10-03 13:40 UTC
### Describe the bug

Links in messages and room topics are highlighted (blue, underlined), but unclickable/untappable. Disabling touchscreen mode makes tapping the links open them in the browser.

### To Reproduce

1. Go to a chat while touchscreen mode is enabled, using a mobile device.
2. Click on a link.
3. See that nothing happens.

### What happened?

zilch.

### Expected behavior

A browser to be opened and the link to be followed.

### Version

0.8.2-05c1d1b8ac

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

Phosh

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment] 2021-11-11 03:37
I can't reproduce this, strangely enough. Can you still reproduce this with the latest master branch?

**Comment by SamuelNorbury** [comment] 2021-11-11 08:09
Hi, I'm still running the same version as in the initial issue, as it hasn't been updated in the postmarketOS/alpine repositories. I sadly won't have time to build the latest master commit. We'll have to take your word that it is fixed in the master branch, feel free to close the issue if it is fixed there.

In the meantime, as a workaround, I've been using the application in non-touchscreen mode, which works really well, actually.

**Comment by deepbluev7** [comment] 2021-11-11 20:38
Okay, I'll close it then. If you can repro after an update, feel free to reopen!

**Closed by deepbluev7** 2021-11-11 20:38 UTC
Labels: bug
