### ISSUE TITLE
The application closes

### ISSUE THREAD

**Issue by Joselpdj** [Nheko-Reborn/nheko#209] opened 2020-05-28 08:18 UTC
I have tried the version 0.7.1, and when I import the keys for view the encrypted messages, the app close and appears a archive "nheko-backtrace.dump" in the appimage folder.

Tested in Mageia Plasma 7.1

**Comment by redsky17** [comment] 2020-05-28 14:19
Would you be comfortable with running the flatpak via gdb and generating a thread dump for us?

**Comment by deepbluev7** [comment] 2020-11-26 03:06
Since no info was provided and I haven't managed to reproduce it, I will close this for now. Especially since I am reworking that code atm, so any crash will probably be either new or not reproducable anymore.

**Closed by deepbluev7** 2020-11-26 03:06 UTC
