### ISSUE TITLE
Spell checking support via KDE/Sonnet (Qt compatible) or other spell checking library

### ISSUE THREAD

**Issue by wapsi** [Nheko-Reborn/nheko#1119] opened 2022-07-19 11:18 UTC
### The Problem

It seems that Nheko does not support spell checking while I'm typing my message.

### The Solution

Use KDE's Qt Sonnet library (https://github.com/KDE/sonnet, as optionally dependency, not mandatory) to achieve proper and feature rich spell checking. Sonnet supports even spell checking of multiple different languages simultaneously, which is quite nice feature as well. And it supports different spell checking backends, like hspell, aspell, hunspell, and voikko.

The language settings could be obtained from the DE settings, or it could be a app specific setting inside Nheko's settings.

### Alternatives

There is another good library to provide spell checking: libenchant / libenchant2, but it's more common in GTK applications.

### Additional context

Using of "dummy" dictionary based spell checking is not good idea, because there are few languages that can't be properly spell checked by using static dictionaries (like Finnish and Hungary). So using of some existing, feature rich spell checking library is the way to go.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by LorenDB** [comment] 2022-07-20 00:19
Duplicate of #174

**Closed** 2022-07-20 00:19 UTC
Labels: enhancement
