### ISSUE TITLE
Can't seem to log in to an account on a homeserver with password-based authentication

### ISSUE THREAD

**Issue by Linerly** [Nheko-Reborn/nheko#1268] opened 2023-01-07 15:33 UTC
### Describe the bug

I tried logging in to my account (in this case on nitro.chat) but it seems to fail getting the `.well-known` data, [even though it exists](https://nitro.chat/.well-known/matrix/client)

Once it gave up, it did fill the homeserver URL with `nitro.chat`, but after entering the password, I can't seem to click on the `LOGIN` button

### To Reproduce

1. Launch Nheko
2. Try to log in to an account that only provides password-based authentication
3. Notice that the `LOGIN` button is unclickable

### What happened?

The login button doesn't work at all when trying to log in to an account on a homeserver that only provides password-based authentication

### Expected behavior

The button works normally, allowing the user to log in

### Version

0.10.2-82e5fa1b

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

KDE Plasma

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
[2023-01-07 22:31:37.124] [net] [error] Autodiscovery failed. Unknown error when requesting .well-known. 0 6
```

**Comment by deepbluev7** [comment] 2023-01-07 15:36
Error 6 means, that it couldn't resolve the host. Possibly that also didn't work when entering the home address manually?

Depending on what platform you are on, this could be because of https://github.com/curl/curl/issues/10146

**Comment by Linerly** [comment] 2023-01-07 16:26
I take a look at #1254 and there is a suggestion to use `curl-git` instead of `curl`, and now it can log in

**Comment by deepbluev7** [comment] 2023-01-07 16:37
Duplicate of #1254

**Closed by deepbluev7** 2023-01-07 16:37 UTC
Labels: bug
