### ISSUE TITLE
Popup menu position shifted by scaling factor when using kvantum on HiDPI

### ISSUE THREAD

**Issue by joe-batt** [Nheko-Reborn/nheko#1141] opened 2022-08-03 08:21 UTC
### Describe the bug

When using kvantum on a scaled display the popup position is multiplied by the scaling factor. 
This means for a scaling factor of 2, right-clicking a message in the center of the screen will have the menu bottom right corner of the screen, this means anything context menus outside the upper left quadrant of the screen are unusable (e.g. the "Start New Chat"-Menu). For me this effect only appears in nheko, other QT application are fine, but also only when using kvantum.

### To Reproduce

1. run `QT_STYLE_OVERRIDE=kvantum QT_SCREEN_SCALE_FACTORS=2 nheko`
2. right-click somewhere in the contact list to open the menu

### Version

0.10.0

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.2

### Desktop Environment

i3

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment] 2022-08-03 14:22
Duplicate of https://github.com/Nheko-Reborn/nheko/issues/618

**Closed by deepbluev7** 2022-08-03 14:22 UTC
Labels: bug
