### ISSUE TITLE
v0.10.2: Installation error on registry (matrix protocol registration)

### ISSUE THREAD

**Issue by Darthagnon** [Nheko-Reborn/nheko#1196] opened 2022-09-29 11:05 UTC
### Describe the bug

Installation, whether run as Admin or not, fails with an error on Windows when it tries to register the Matrix protocol in the registry.

### To Reproduce

1. Install Nheko on Windows (run as admin or not)
2. On installation, an error message will pop up, and you cannot proceed with installation without ignoring it.

### Expected behavior

It should pick up the installation folder location of the previous installation and update that, and ignore re-registering in the registry if it is an update. Or, it should work. Caveat: I haven't shut down my Win10 v1709 machine in a few days.

### Screenshots

![nheko-v0 10 2-installer_gPccxaPMYM](https://user-images.githubusercontent.com/20792748/193015339-a70b30d1-1d29-4972-b4a4-06203852fc45.png)

### Version

0.10.2

### Operating system

Windows

### Installation method

Windows download

### Qt version

I hope it's still Qt 5, but Windows doesn't use system-wide Qt

### Desktop Environment

Win10 v1709

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment] 2022-09-30 12:39
Yes, this is a known issue with our windows installer. I don't know regedit enough to figure out how to not make it error in that case.

**Comment by LorenDB** [comment] 2023-03-01 19:42
Duplicate of #762

**Closed by LorenDB** 2023-03-01 19:42 UTC
Labels: bug
