### ISSUE TITLE
URL Preview for both normal and E2EE Rooms/DMs

### ISSUE THREAD

**Issue by AppTester7** [Nheko-Reborn/nheko#1668] opened 2024-01-22 18:18 UTC
### The Problem

Most of the time people only copy/paste url links, they
seldom bother to also copy and paste a youtube video name/title

### The Solution

Have ability to Preview URLs in both non-E2EE and E2EE Rooms/DMs (example: YouTube video links) so
you can see the Video Description and the Video thumbnail

Searching through posted video links with video thumbnails immediately makes it s lot easier and much
faster to quickly locate the desired video to watch

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by LorenDB** [comment] 2024-01-22 18:50
Duplicate of #561

**Closed by LorenDB** 2024-01-22 18:50 UTC
Labels: enhancement
