### ISSUE TITLE
"Another instance of Nheko is running"

### ISSUE THREAD

**Issue by abma** [Nheko-Reborn/nheko#158] opened 2020-03-25 08:58 UTC
### Describe the bug

When running nheko one time under different user logins on linux, the error message "Another instance of Nheko is running" pops up. 

### To Reproduce
1. Login as user a on computer, start nheko
2. Login as user b on the same computer nheko
-> error message

- Nheko version: 0.6.3-2 
- Installation method: apt
- Operating System: debian 10

the check for other instances is wrong: it should just check if the config directory is in use, i.e. use a lockfile.

**Comment by deepbluev7** [comment] 2020-03-25 09:11
This is a duplicate of #113 and fixed in the current development version (0.7.0). While we don't currently check for the config file, running multiple instances as different users shouldn't be an issue anymore. Also be aware, that you are not even on the latest stable version, so please make sure any bugs you report are not already fixed in the latest release (although this particular one is still only fixed in the dev version...).

I'll close this as a duplicate for now, please reopen it, if you still have issues with the current dev version (like running multiple instances as the same user with different config files or similar).

**Closed by deepbluev7** 2020-03-25 09:11 UTC
Labels: bug
