### ISSUE TITLE
Problem with formatting into numbered list automatically

### ISSUE THREAD

**Issue by hyperbel** [Nheko-Reborn/nheko#1566] opened 2023-09-24 10:35 UTC
### Describe the bug

When someone sends a message with an arbitrary number and a '.' right after at the beginning, it is interpreted as a numbered list and the message is shown with a 1. at the beginning, instead of the intended number.

### To Reproduce

1. Send a message starting with an arbitraty number and a '.' following it
2. Look at the message you just sent

### What happened?

When discussing Intel processors, someone claimed that the 9. Gen is too expensive. On my side, it appeared, as if they said that 1. Gen is too expensive.

### Expected behavior

The correct number should have appeared. 

### Screenshots

![markdown-render-bug](https://github.com/Nheko-Reborn/nheko/assets/25338593/aba959e5-5dcf-4934-b2ab-2ef9a13e8e38)
![image](https://github.com/Nheko-Reborn/nheko/assets/25338593/8462bc36-4bfd-4853-a99e-4b5491167d01)

### Version

0.11.3

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

awesome wm

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment] 2023-10-10 11:18
duplicate of https://github.com/Nheko-Reborn/nheko/issues/793

Also already fixed in Qt6.6, so this will work once you have Qt6.6: https://codereview.qt-project.org/c/qt/qtbase/+/460444

**Closed by deepbluev7** 2023-10-10 11:18 UTC
Labels: bug
