### ISSUE TITLE
Crash on login

### ISSUE THREAD

**Issue by avdb13** [Nheko-Reborn/nheko#987] opened 2022-03-11 17:11 UTC
### Describe the bug

Nheko is crashing when I'm trying to use my homeserver.

### To Reproduce

1. Open Nheko
2. Enter my username in the form
3. Get a crash

### What happened?

```
[2022-03-11 19:04:52.321] [ui] [info] Restoring window size 3396x1379
[2022-03-11 19:04:52.405] [ui] [info] WebRTC: initialised GStreamer 1.18.4
[2022-03-11 19:04:52.615] [ui] [info] Loaded jdenticon plugin.
[2022-03-11 19:04:53.581] [ui] [info] starting nheko 0.9.1
[2022-03-11 19:04:56.209] [qml] [warning] failed to create compose table (:0, )
[2022-03-11 19:05:00.588] [net] [info] Autodiscovery: No .well-known.
terminate called after throwing an instance of 'std::invalid_argument'
  what():  v1.1: invalid version
Error: signal 6:
nheko(_Z17stacktraceHandleri+0x3d)[0x556d0729ec8d]
/lib64/libc.so.6(+0x3dfa0)[0x7f1c88d7afa0]
/lib64/libc.so.6(+0x8ba0c)[0x7f1c88dc8a0c]
/lib64/libc.so.6(raise+0x12)[0x7f1c88d7aef2]
/lib64/libc.so.6(abort+0xcf)[0x7f1c88d6544b]
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libstdc++.so.6(+0x9d8be)[0x7f1c890c78be]
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libstdc++.so.6(+0xa9608)[0x7f1c890d3608]
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libstdc++.so.6(+0xa9673)[0x7f1c890d3673]
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libstdc++.so.6(+0xa9913)[0x7f1c890d3913]
/usr/lib64/libmatrix_client.so.0.6.1(+0x15d62a)[0x7f1c8b7ec62a]
/usr/lib64/libmatrix_client.so.0.6.1(_ZZN3mtx4http6Client16prepare_callbackINS_9responses8VersionsEEESt8functionIFvRKSt8optionalISt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESD_N6coeurl11header_lessESaISt4pairIKSD_SD_EEEERKSt17basic_string_viewIcSB_EiiEES5_IFvRKT_SN_RKS6_INS0_11ClientErrorEEEEENKUlSN_SR_iiE_clESN_SR_ii+0x200)[0x7f1c8b8894b0]
/usr/lib64/libmatrix_client.so.0.6.1(+0x15fda3)[0x7f1c8b7eeda3]
/usr/lib64/libcoeurl.so.0(_ZN6coeurl6Client14remove_requestEPNS_7RequestE+0x358)[0x7f1c8b415498]
/usr/lib64/libcoeurl.so.0(_ZN6coeurl6Client16check_multi_infoEv+0x165)[0x7f1c8b4156a5]
/usr/lib64/libcoeurl.so.0(_ZN6coeurl6Client8event_cbEisPv+0x5e)[0x7f1c8b4157ee]
/usr/lib64/libevent_core-2.1.so.7(+0x1a690)[0x7f1c889e6690]
/usr/lib64/libevent_core-2.1.so.7(event_base_loop+0x53f)[0x7f1c889e727f]
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libstdc++.so.6(+0xd6160)[0x7f1c89100160]
/lib64/libc.so.6(+0x89cd7)[0x7f1c88dc6cd7]
/lib64/libc.so.6(clone+0x40)[0x7f1c88e4ac40]
Aborted
```

### Expected behavior

I just want to login and use Nheko like I've always been doing.

### Version

0.9.1

### Operating system

Linux

### Installation method

Local build

### Qt version

5.15.2-r16

### C++ compiler

gcc-11.2.1

### Desktop Environment

DWM

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
Not relevant here
```

### Backtrace

```shell
No debug symbols
```

**Comment by deepbluev7** [comment] 2022-03-11 22:19
Duplicate of #957

**Comment by deepbluev7** [comment] 2022-03-11 22:19
Please update

**Closed by deepbluev7** 2022-03-11 22:19 UTC
Labels: bug
