### ISSUE TITLE
nheko using 100% CPU

### ISSUE THREAD

**Issue by blitz** [Nheko-Reborn/nheko#79] opened 2019-07-17 20:00 UTC
### System:

- Nheko version: 0.6.4 | Linux
- Installation method: dnf install nheko
- Operating System: Fedora 30
- Desktop Environment: Gnome on Wayland (Fedora default)

### Actual behavior

After a while of usage Nheko will start to use permanently 100% CPU. No other negative symptom is visible.

### Expected behavior

Nheko is not permanently using 100% CPU.

### Steps to reproduce

Unclear. It eventually happens if I leave Nheko running in the background.

### Logs
N/A

**Comment by redsky17** [comment] 2019-07-18 20:25
I'm pretty sure this is caused by SSL connection issues related to #52.  It sounds like the same symptoms anyway.

**Comment by MarcusMoeller** [comment] 2019-07-24 04:54
I have noticed the same effect on a GNOME desktop. Not with KDE Plasma though. For me it was not related to things like suspend/resume, but I have noticed that at the same time the Tray icon was no longer displayed, still the application has run in bg.

**Comment by Mikaela** [comment] 2019-09-17 14:01
I noticed this on i3 on Debian Testing with nheko 0.6.4 1b34b53 installed from Flathub.

![Screenshot from 2019-09-17 16-50-52](https://user-images.githubusercontent.com/831184/65047751-a9805a00-d96b-11e9-8e2c-a2ce8ac4f718.png)

I installed Nheko this morning and put it to autostart. Later I booted my laptop and let it be in the background for maybe half an hour and I started idly wondering why I keep hearing the laptop fan louder than usually and some time later checked htop and noticed this issue.

Are the logs stored somewhere? I attempted to check issue template and only found a GitHub warning:

> You are using an old version of issue templates. Please update to the new issue template workflow. Learn more

* https://help.github.com/articles/about-issue-and-pull-request-templates

**Comment by deepbluev7** [comment] 2020-02-13 15:19
So, I never hit that bug again, so I'm marking this as fixed on 0.7.0. Please reopen, if someone can still reproduce!

**Closed by deepbluev7** 2020-02-13 15:19 UTC
Labels: bug

**Comment by Mikaela** [comment] 2020-02-13 15:33
0.7.0 is not listed on the [releases](https://github.com/Nheko-Reborn/nheko/releases) page and seems to be unavailable on [the flatpak](https://github.com/flathub/io.github.NhekoReborn.Nheko)?

**Comment by deepbluev7** [comment] 2020-02-13 16:01
Yes, 0.7.0 was not released yet, but I'm kinda doing some housekeeping to sort out, which bugs I still want to fix before releasing 0.7.0. Sorry about that!
