### ISSUE TITLE
Weird context menu behaviour on Wayland

### ISSUE THREAD

**Issue by brausepulver** [Nheko-Reborn/nheko#1102] opened 2022-06-18 21:26 UTC
### Describe the bug

Context menus have all sorts of weird behaviour on Wayland which isn't present on Xorg.

- Don't open at the location of the cursor
- Open as seperate window
- Don't close when clicking away and instead move to background
- Don't open when another context menu is already in background (this can also crash nheko)

### To Reproduce

1. Open any context menu, e.g. for a room in the rooms list. Context menus will always open in the same place, rather than at the location of the cursor.
2. Click somewhere else, so that the menu is moved to background.
3. Close the window containing the menu.
4. Attempt to open the same context menu. This crashes nheko.

### Expected behavior

Same as on Xorg

### Screenshots

Context menus are opened as individual windows:
![image](https://user-images.githubusercontent.com/34420739/174457456-3b302a5c-79a4-4cec-92d6-3769f852cf78.png)

### Version

0.9.3-9bac429

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.3

### C++ compiler

gcc 11.2.1

### Desktop Environment

Gnome 41.3

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
Gdk-Message: 23:09:30.135: Window 0x559dc5a4c930 is a temporary window without parent, application will not be able to position it on screen.

(nheko:29235): Gdk-WARNING **: 23:09:30.135: Couldn't map as window 0x559dc5a4c930 as popup because it doesn't have a parent
Gdk-Message: 23:09:35.284: Window 0x559dc7f4e840 is a temporary window without parent, application will not be able to position it on screen.

(nheko:29235): Gdk-WARNING **: 23:09:35.284: Couldn't map as window 0x559dc7f4e840 as popup because it doesn't have a parent

(nheko:29235): Gtk-CRITICAL **: 23:09:38.021: gtk_window_set_accept_focus: assertion 'GTK_IS_WINDOW (window)' failed
Error: signal 11:
nheko(_Z17stacktraceHandleri+0x3b)[0x559dc3bf1b8b]
/lib64/libc.so.6(+0x3d730)[0x7f0cc4a46730]
/usr/lib64/libgtk-3.so.0(+0x3b3ba0)[0x7f0cc09b3ba0]
/usr/lib64/libgtk-3.so.0(+0x250ceb)[0x7f0cc0850ceb]
/usr/lib64/libgtk-3.so.0(+0x251685)[0x7f0cc0851685]
/usr/lib64/libgtk-3.so.0(gtk_menu_popup+0x76)[0x7f0cc0851cc6]
/usr/lib64/qt5/plugins/platformthemes/libqgtk3.so(+0x186e2)[0x7f0cc0f9d6e2]
/usr/lib64/qt5/qml/Qt/labs/platform/libqtlabsplatformplugin.so(+0x1fc78)[0x7f0c7c721c78]
/usr/lib64/qt5/qml/Qt/labs/platform/libqtlabsplatformplugin.so(+0x2f02b)[0x7f0c7c73102b]
/usr/lib64/libQt5Qml.so.5(+0x2bc34d)[0x7f0cc68bc34d]
/usr/lib64/libQt5Qml.so.5(_ZNK3QV413QObjectMethod12callInternalEPKNS_5ValueES3_i+0x84c)[0x7f0cc679ee3c]
/usr/lib64/libQt5Qml.so.5(_ZN3QV47Runtime28CallQmlContextPropertyLookup4callEPNS_15ExecutionEngineEjPNS_5ValueEi+0xa2)[0x7f0cc67ccfc2]
/usr/lib64/libQt5Qml.so.5(+0x1b93e8)[0x7f0cc67b93e8]
/usr/lib64/libQt5Qml.so.5(+0x1bdc0f)[0x7f0cc67bdc0f]
/usr/lib64/libQt5Qml.so.5(+0x153950)[0x7f0cc6753950]
/usr/lib64/libQt5Qml.so.5(+0x1bae21)[0x7f0cc67bae21]
/usr/lib64/libQt5Qml.so.5(+0x1bdc0f)[0x7f0cc67bdc0f]
/usr/lib64/libQt5Qml.so.5(_ZN3QV48Function4callEPKNS_5ValueES3_iPKNS_16ExecutionContextE+0x17e)[0x7f0cc6752bae]
/usr/lib64/libQt5Qml.so.5(_ZN24QQmlJavaScriptExpression8evaluateEPN3QV48CallDataEPb+0x215)[0x7f0cc68d6945]
/usr/lib64/libQt5Qml.so.5(_ZN25QQmlBoundSignalExpression8evaluateEPPv+0x3b1)[0x7f0cc6888e21]
/usr/lib64/libQt5Qml.so.5(+0x289ff0)[0x7f0cc6889ff0]
/usr/lib64/libQt5Qml.so.5(_ZN12QQmlNotifier10emitNotifyEP20QQmlNotifierEndpointPPv+0x225)[0x7f0cc68bbe05]
/usr/lib64/libQt5Core.so.5(+0x2a9129)[0x7f0cc52a9129]
/usr/lib64/libQt5Quick.so.5(_ZN16QQuickTapHandler12singleTappedEP16QQuickEventPoint+0x42)[0x7f0cc700c5d2]
/usr/lib64/libQt5Quick.so.5(_ZN16QQuickTapHandler10setPressedEbbP16QQuickEventPoint+0x9bc)[0x7f0cc6fb141c]
/usr/lib64/libQt5Quick.so.5(_ZN24QQuickSinglePointHandler22handlePointerEventImplEP18QQuickPointerEvent+0x50)[0x7f0cc6fb0390]
/usr/lib64/libQt5Quick.so.5(_ZN20QQuickPointerHandler18handlePointerEventEP18QQuickPointerEvent+0x588)[0x7f0cc6faf2b8]
/usr/lib64/libQt5Quick.so.5(_ZN19QQuickWindowPrivate17deliverMouseEventEP23QQuickPointerMouseEvent+0x6d3)[0x7f0cc6e71d93]
/usr/lib64/libQt5Quick.so.5(_ZN19QQuickWindowPrivate19deliverPointerEventEP18QQuickPointerEvent+0x5a)[0x7f0cc6e72f1a]
/usr/lib64/libQt5Gui.so.5(_ZN7QWindow5eventEP6QEvent+0x115)[0x7f0cc5922a85]
/usr/lib64/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x7f)[0x7f0cc5f6364f]
/usr/lib64/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x128)[0x7f0cc5276d68]
/usr/lib64/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE+0x6ad)[0x7f0cc591773d]
/usr/lib64/libQt5Gui.so.5(_ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0xab)[0x7f0cc58f832b]
/usr/lib64/libQt5WaylandClient.so.5(+0xac5b0)[0x7f0cc11445b0]
/usr/lib64/libglib-2.0.so.0(g_main_context_dispatch+0x186)[0x7f0cc651cb06]
/usr/lib64/libglib-2.0.so.0(+0x53fe8)[0x7f0cc651cfe8]
/usr/lib64/libglib-2.0.so.0(g_main_context_iteration+0x2f)[0x7f0cc651d09f]
/usr/lib64/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x68)[0x7f0cc52c6e78]
/usr/lib64/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x123)[0x7f0cc52757f3]
/usr/lib64/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x90)[0x7f0cc527db10]
nheko(main+0xcf3)[0x559dc39285f3]
/lib64/libc.so.6(+0x2931a)[0x7f0cc4a3231a]
/lib64/libc.so.6(__libc_start_main+0x7c)[0x7f0cc4a323cc]
nheko(_start+0x21)[0x559dc3929451]
Error: signal 6:
nheko(_Z17stacktraceHandleri+0x3b)[0x559dc3bf1b8b]
/lib64/libc.so.6(+0x3d730)[0x7f0cc4a46730]
/lib64/libc.so.6(+0x88f1c)[0x7f0cc4a91f1c]
/lib64/libc.so.6(raise+0x12)[0x7f0cc4a46692]
nheko(_Z17stacktraceHandleri+0xf1)[0x559dc3bf1c41]
/lib64/libc.so.6(+0x3d730)[0x7f0cc4a46730]
/usr/lib64/libgtk-3.so.0(+0x3b3ba0)[0x7f0cc09b3ba0]
/usr/lib64/libgtk-3.so.0(+0x250ceb)[0x7f0cc0850ceb]
/usr/lib64/libgtk-3.so.0(+0x251685)[0x7f0cc0851685]
/usr/lib64/libgtk-3.so.0(gtk_menu_popup+0x76)[0x7f0cc0851cc6]
/usr/lib64/qt5/plugins/platformthemes/libqgtk3.so(+0x186e2)[0x7f0cc0f9d6e2]
/usr/lib64/qt5/qml/Qt/labs/platform/libqtlabsplatformplugin.so(+0x1fc78)[0x7f0c7c721c78]
/usr/lib64/qt5/qml/Qt/labs/platform/libqtlabsplatformplugin.so(+0x2f02b)[0x7f0c7c73102b]
/usr/lib64/libQt5Qml.so.5(+0x2bc34d)[0x7f0cc68bc34d]
/usr/lib64/libQt5Qml.so.5(_ZNK3QV413QObjectMethod12callInternalEPKNS_5ValueES3_i+0x84c)[0x7f0cc679ee3c]
/usr/lib64/libQt5Qml.so.5(_ZN3QV47Runtime28CallQmlContextPropertyLookup4callEPNS_15ExecutionEngineEjPNS_5ValueEi+0xa2)[0x7f0cc67ccfc2]
/usr/lib64/libQt5Qml.so.5(+0x1b93e8)[0x7f0cc67b93e8]
/usr/lib64/libQt5Qml.so.5(+0x1bdc0f)[0x7f0cc67bdc0f]
/usr/lib64/libQt5Qml.so.5(+0x153950)[0x7f0cc6753950]
/usr/lib64/libQt5Qml.so.5(+0x1bae21)[0x7f0cc67bae21]
/usr/lib64/libQt5Qml.so.5(+0x1bdc0f)[0x7f0cc67bdc0f]
/usr/lib64/libQt5Qml.so.5(_ZN3QV48Function4callEPKNS_5ValueES3_iPKNS_16ExecutionContextE+0x17e)[0x7f0cc6752bae]
/usr/lib64/libQt5Qml.so.5(_ZN24QQmlJavaScriptExpression8evaluateEPN3QV48CallDataEPb+0x215)[0x7f0cc68d6945]
/usr/lib64/libQt5Qml.so.5(_ZN25QQmlBoundSignalExpression8evaluateEPPv+0x3b1)[0x7f0cc6888e21]
/usr/lib64/libQt5Qml.so.5(+0x289ff0)[0x7f0cc6889ff0]
/usr/lib64/libQt5Qml.so.5(_ZN12QQmlNotifier10emitNotifyEP20QQmlNotifierEndpointPPv+0x225)[0x7f0cc68bbe05]
/usr/lib64/libQt5Core.so.5(+0x2a9129)[0x7f0cc52a9129]
/usr/lib64/libQt5Quick.so.5(_ZN16QQuickTapHandler12singleTappedEP16QQuickEventPoint+0x42)[0x7f0cc700c5d2]
/usr/lib64/libQt5Quick.so.5(_ZN16QQuickTapHandler10setPressedEbbP16QQuickEventPoint+0x9bc)[0x7f0cc6fb141c]
/usr/lib64/libQt5Quick.so.5(_ZN24QQuickSinglePointHandler22handlePointerEventImplEP18QQuickPointerEvent+0x50)[0x7f0cc6fb0390]
/usr/lib64/libQt5Quick.so.5(_ZN20QQuickPointerHandler18handlePointerEventEP18QQuickPointerEvent+0x588)[0x7f0cc6faf2b8]
/usr/lib64/libQt5Quick.so.5(_ZN19QQuickWindowPrivate17deliverMouseEventEP23QQuickPointerMouseEvent+0x6d3)[0x7f0cc6e71d93]
/usr/lib64/libQt5Quick.so.5(_ZN19QQuickWindowPrivate19deliverPointerEventEP18QQuickPointerEvent+0x5a)[0x7f0cc6e72f1a]
/usr/lib64/libQt5Gui.so.5(_ZN7QWindow5eventEP6QEvent+0x115)[0x7f0cc5922a85]
/usr/lib64/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x7f)[0x7f0cc5f6364f]
/usr/lib64/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x128)[0x7f0cc5276d68]
/usr/lib64/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE+0x6ad)[0x7f0cc591773d]
/usr/lib64/libQt5Gui.so.5(_ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0xab)[0x7f0cc58f832b]
/usr/lib64/libQt5WaylandClient.so.5(+0xac5b0)[0x7f0cc11445b0]
/usr/lib64/libglib-2.0.so.0(g_main_context_dispatch+0x186)[0x7f0cc651cb06]
/usr/lib64/libglib-2.0.so.0(+0x53fe8)[0x7f0cc651cfe8]
/usr/lib64/libglib-2.0.so.0(g_main_context_iteration+0x2f)[0x7f0cc651d09f]
/usr/lib64/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x68)[0x7f0cc52c6e78]
/usr/lib64/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x123)[0x7f0cc52757f3]
/usr/lib64/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x90)[0x7f0cc527db10]
nheko(main+0xcf3)[0x559dc39285f3]
/lib64/libc.so.6(+0x2931a)[0x7f0cc4a3231a]
/lib64/libc.so.6(__libc_start_main+0x7c)[0x7f0cc4a323cc]
nheko(_start+0x21)[0x559dc3929451]
Aborted
```

**Comment by deepbluev7** [comment] 2022-06-18 22:48
Duplicate of #940 #831 #618 and #571 I think?

**Comment by brausepulver** [comment] 2022-06-19 00:17
Ah okay my bad. This only happens to me when running the DE under Wayland though, regardless of whether nheko runs under Xwayland or not.

**Comment by deepbluev7** [comment] 2022-06-19 00:40
Yes, most of those issues are wayland specific, although some can also happen on some X11 WMs. Most of them are upstream qt bugs and half of them are fixed for Qt6.

**Closed by deepbluev7** 2022-06-19 00:40 UTC
Labels: bug
