### ISSUE TITLE
Some spaces show an extra room in the sidebar

### ISSUE THREAD

**Issue by tastytea** [Nheko-Reborn/nheko#954] opened 2022-02-21 08:01 UTC
### Describe the bug

Some spaces have 1, sometimes more extra rooms in the room list. There is no preview available, it has no avatar and it is not joinable. Spaces in which I observed this phenomenon:

- `#fedibikes-de:tchncs.de`
- `#flameshot-org:matrix.org`
- `#gitea-space:matrix.org` has even 3
- `#space_fahrrad:matrix.org`
- `#activitypub-community:codelutin.com`

### To Reproduce

1. Join [#flameshot-org:matrix.org](https://matrix.to/#/#flameshot-org:matrix.org)
2. Look at room list
3. Compare list with the list in Element

### Version

0.9.1-ff4334d5

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.2

### C++ compiler

gcc 11.2.0

### Desktop Environment

n/a

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment] 2022-02-21 11:56
I don't think this is a Nheko bug, I actually believe some client put an unjoinable room there. The summary API doesn't give a preview for those. If a client wants hidden rooms in the space, they should add it only using parent events, not child events.

**Comment by deepbluev7** [comment] 2022-07-20 09:16
This is not a bug in Nheko from my understanding, so I will close this.

**Closed by deepbluev7** 2022-07-20 09:16 UTC
Labels: bug
