### ISSUE TITLE
Nheko crashes after about 30 seconds after opening.

### ISSUE THREAD

**Issue by trueauracoral** [Nheko-Reborn/nheko#981] opened 2022-03-09 05:40 UTC
### Describe the bug

For the whole day today, even after restarting my computer. Nheko has been acting very strange. I will open nheko up, it works fine, syncs messages, I can make make a message and then **boom**, 30 seconds has passed and nheko crashes itself. 

### To Reproduce

1. Open nheko
2. Start using the application or do nothing
3. After 30 seconds nheko closed itself.

### Expected behavior

It should work as usual not closing itself down all of a sudden.

### Screenshots

https://user-images.githubusercontent.com/87541524/157379193-4861b1da-594c-44b0-9acb-643ef19c3265.mp4

### Version

The newest windows version

### Operating system

Windows

### Installation method

Windows download

### Did you use profiles?

- [X] Profiles used?

### Relevant log output

```shell
[2022-03-06 22:23:40.256] [qml] [warning] DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="Fixedsys", pointsize=6.75, pixelsize=15, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("Fixedsys", lfWidth=0, lfHeight=-15) dpi=144 (:0, )
[2022-03-06 22:23:40.307] [qml] [warning] DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="Fixedsys", pointsize=15, pixelsize=20, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("Fixedsys", lfWidth=0, lfHeight=-20) dpi=144 (:0, )
[2022-03-06 22:24:30.519] [qml] [warning] DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="8514oem", pointsize=15, pixelsize=20, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("8514oem", lfWidth=0, lfHeight=-20) dpi=144 (:0, )
[2022-03-06 22:24:30.542] [qml] [warning] DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="Fixedsys", pointsize=15, pixelsize=20, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("Fixedsys", lfWidth=0, lfHeight=-20) dpi=144 (:0, )
[2022-03-06 22:25:03.218] [qml] [warning] qrc:/qml/delegates/ImageMessage.qml:27:5: QML Image: Blurhash needs size request (qrc:/qml/delegates/ImageMessage.qml:27, )
[2022-03-06 22:25:24.509] [ui] [info] Playing movie with size: 2687725, true
[2022-03-06 22:25:24.510] [ui] [info] Playing movie with size: 2687725, true
[2022-03-06 22:25:25.382] [ui] [info] Playing movie with size: 2687725, true
[2022-03-06 22:25:25.384] [ui] [info] Playing movie with size: 2687725, true
[2022-03-06 22:25:32.132] [qml] [warning] qrc:/qml/delegates/ImageMessage.qml:27:5: QML Image: Blurhash needs size request (qrc:/qml/delegates/ImageMessage.qml:27, )
[2022-03-06 22:25:33.124] [ui] [info] Pasting image with size: 406x367, format: image/png
[2022-03-06 22:26:20.296] [qml] [warning] qrc:/qml/delegates/ImageMessage.qml:27:5: QML Image: Blurhash needs size request (qrc:/qml/delegates/ImageMessage.qml:27, )
[2022-03-06 22:26:42.134] [net] [error] sync error: (parser: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal: )
[2022-03-06 22:26:43.701] [ui] [info] Restoring window size 687x607
[2022-03-06 22:26:43.935] [ui] [info] Loaded jdenticon plugin.
[2022-03-06 22:26:44.476] [ui] [info] starting nheko 0.9.1-dfab0c92
```

**Comment by deepbluev7** [comment] 2022-03-09 15:18
Duplicate of #957 

Please update to 0.9.1-1

**Closed by deepbluev7** 2022-03-09 15:18 UTC
Labels: bug
