### ISSUE TITLE
Dark theme issues

### ISSUE THREAD

**Issue by KAMiKAZOW** [Nheko-Reborn/nheko#252] opened 2020-08-02 08:27 UTC
Kinda the same as #118 but under Windows 10:

![image](https://user-images.githubusercontent.com/3259076/89118958-8b034e80-d4aa-11ea-84b4-4ca3606ab27d.png)

**Comment by redsky17** [comment] 2020-10-09 17:51
I definitely think this is a duplicate of #118.  I'm going to close this in favor of that one.

**Closed by redsky17** 2020-10-09 17:51 UTC
Labels: bug

**Comment by KAMiKAZOW** [comment] 2020-10-09 19:41
How is a fixed Linux bug the same as an unfixed Windows bug? I opened both and I know for a fact that the Linux version was working fine after #125.
