### ISSUE TITLE
Context menus show up at wrong location when monitor scaling is enabled

### ISSUE THREAD

**Issue by evren320** [Nheko-Reborn/nheko#1138] opened 2022-08-01 16:37 UTC
### Describe the bug

Right click menu or three dots menus show up at wrong location

### To Reproduce

Open a chat page, click on three dots, or right click on a message.
You will see menu popup appear at wrong location.
Seems location depends on the scaling factor and window position.

### Expected behavior

Popup should appear near clicked area

### Version

0.10.0

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

KDE Plasma desktop

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment] 2022-08-01 21:27
Duplicate of #618

**Closed by deepbluev7** 2022-08-01 21:27 UTC
Labels: bug
