### ISSUE TITLE
Nheko 0.9.0 doesn't open

### ISSUE THREAD

**Issue by VarLad** [Nheko-Reborn/nheko#816] opened 2021-11-19 08:46 UTC
### Describe the bug

Nheko doesn't open when I installed the latest version from Flathub. 

### To Reproduce

1. In Fedora 35, GNOME41
2. Install with `flatpak run io.github.NhekoReborn.Nheko`
3. Run with `flatpak run io.github.NhekoReborn.Nheko`

### What happened?

Its stuck on this window
![nheko](https://user-images.githubusercontent.com/51269425/142592773-62102e2d-204f-4fd4-916f-ae200d5d1cf2.png)

The logfiles read this 
```
QSocketNotifier: Can only be used with threads started with QThread
[2021-11-19 14:11:31.584] [ui] [info] Restoring window size 1068x841
[2021-11-19 14:11:31.641] [ui] [info] WebRTC: initialised GStreamer 1.18.5
[2021-11-19 14:11:32.009] [ui] [info] Loaded jdenticon plugin.
[2021-11-19 14:11:32.243] [ui] [info] starting nheko 0.9.0-f32acdd
```

### Expected behavior

Nheko opens and runs

### Version

0.9.0-f32acdd

### Operating system

Linux

### Installation method

Flathub

### Desktop Environment

GNOME41 

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
[2021-11-19 14:06:17.881] [ui] [info] Restoring window size 0x0
[2021-11-19 14:06:19.849] [ui] [info] WebRTC: initialised GStreamer 1.18.5
[2021-11-19 14:06:20.108] [ui] [info] Loaded jdenticon plugin.
[2021-11-19 14:06:20.453] [ui] [info] starting nheko 0.9.0-f32acdd
[2021-11-19 14:08:58.606] [ui] [info] Restoring window size 1066x839
[2021-11-19 14:09:00.179] [ui] [info] WebRTC: initialised GStreamer 1.18.5
[2021-11-19 14:09:00.377] [ui] [info] Loaded jdenticon plugin.
[2021-11-19 14:09:00.676] [ui] [info] starting nheko 0.9.0-c0b2e8f9
[2021-11-19 14:11:23.446] [ui] [info] Restoring window size 1068x841
[2021-11-19 14:11:25.042] [ui] [info] WebRTC: initialised GStreamer 1.18.5
[2021-11-19 14:11:25.343] [ui] [info] Loaded jdenticon plugin.
[2021-11-19 14:11:25.638] [ui] [info] starting nheko 0.9.0-f32acdd
```
```


### Backtrace

_No response_

**Comment by VarLad** [comment] 2021-11-19 10:06
I can verify that it runs on Fedora Kinoite 35 (KDE Plasma 5.23.2)

**Comment by deepbluev7** [comment] 2021-11-19 12:35
Probably some interaction with the secrets service from Gnome. I'll see, if I can setup a Gnome VM.

**Comment by ptman** [comment] 2021-11-19 19:53
I got "Nheko could not connect to the secure stora to save encryption secrets to. This can have multiple reasons. ..." flatpak as well

**Comment by dessalines** [comment] 2021-11-19 22:04
Same, just got this. This was from an arch install, and running keepassXC, but it still has this error.

**Comment by deepbluev7** [comment] 2021-11-19 22:12
If you get an actual error popup, your keychain might not be reachable. If you use keepassXC, you need to manually enable the secrets store and use the git version of keepassXC, since 2.6.x returns wrong data sometimes.

**Comment by dessalines** [comment] 2021-11-19 22:28
Why not just make the keyring saving optional, and just have it as a warning? I prefer to back up my keys manually anyway.

**Comment by VarLad** [comment] 2021-11-19 23:48
@deepbluev7 For me, there's no error
The above window just goes on endlessly

**Comment by deepbluev7** [comment] 2021-11-19 23:51
The endless loading is what I will try to fix first, the other issue is usually rather a configuration issue, not an issue with our package.

> Why not just make the keyring saving optional, and just have it as a warning? I prefer to back up my keys manually anyway.

We just use that storage to store the cross-signing secrets and the decryption key for the database. If we make it optional, some people will store their messages in plain text by accident, and we wanted to prevent that, because it makes it very easy for an attacker to get access to all your messages.

**Comment by deepbluev7** [comment] 2021-11-22 04:22
Can someone try, if this flatpak fixes it? https://nheko.im/nheko-reborn/nheko/-/jobs/11850/artifacts/browse/build-flatpak/

**Comment by deepbluev7** [comment] 2021-11-22 16:55
Okay, thank you, I will look into that! I am assuming removing ~/.var/app/io.github.NhekoReborn.Nheko/ doesn't fix that?

**Comment by ilyazzz** [comment] 2021-11-22 17:03
Yes, I've tried logging in, removed `~/.var/app/io.github.NhekoReborn.Nheko/` and `~/.local/share/keyring`, restarted the gui session and then tried logging in again - same error.

**Comment by deepbluev7** [comment] 2021-11-22 17:07
Okay, I'll debug some more, thanks again!

**Comment by deepbluev7** [comment] 2021-11-23 01:08
Hm, with the app I linked above, I can't reproduce the bug anymore... ._.

I could try building a version with libsecret 19.1, but I don't understand why the above version fixes it for me, but not for you...

**Comment by ilyazzz** [comment] 2021-11-23 08:44
I'm also having the same error with 0.8.2 installed from the Fedora repos. Cleaning the keyring/configs doesn't help.

**Comment by VarLad** [comment] 2021-11-23 10:02
@deepbluev7 I can verify its working for me
and it looks glorious on GNOME as well! 
Thanks! I hope you can merge it soon

**Comment by nebocamin** [comment] 2021-11-23 13:15
I have the effect too, on raspi 4 ubuntu arm64 and also on pinephone mobian arm64. If you can build easily an arm64 build, I will test it too if you want.

**Comment by deepbluev7** [comment] 2021-11-23 13:43
arm64 build is here: https://nheko.im/nheko-reborn/nheko/-/jobs/11861/artifacts/browse/build-flatpak/

**Comment by ilyazzz** [comment] 2021-11-23 14:00
I'm also getting the same error using the AUR package on arch linux with swaywm (also with gnome-keyring).

**Comment by ilyazzz** [comment] 2021-11-23 14:08
Update: I managed to log in after removing the session from Element, though the initial login took a very long time (also for some reason it dumped an HTML page with a js error in the logs, but I assume that's unrelated)

**Comment by deepbluev7** [comment] 2021-11-24 03:50
I've pushed a flatpak with the fix now, tell me, if that fixes the issues also on flathub :3

**Comment by nebocamin** [comment] 2021-11-25 20:18
after the update it not starting in arm64 anymore. (tested on arm64 ubuntu raspi4 and a mobian pinephone)


`flatpak run io.github.NhekoReborn.Nheko
QSocketNotifier: Can only be used with threads started with QThread
[2021-11-25 21:15:46.620] [ui] [info] Restoring window size 0x0
[2021-11-25 21:15:51.090] [ui] [info] WebRTC: initialised GStreamer 1.18.5

** (nheko:2): CRITICAL **: 21:15:51.298: gst_alsa_device_new: assertion 'caps' failed
[2021-11-25 21:15:52.298] [ui] [info] Loaded jdenticon plugin.
Error: signal 11:
nheko(+0x3af7b0)[0xaaaaac2df7b0]
linux-vdso.so.1(__kernel_rt_sigreturn+0x0)[0xffff9bc1c7dc]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZNK17QQmlPropertyCache8propertyEi+0x10)[0xffff9aff2c74]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x24ae00)[0xffff9b067e00]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x24b09c)[0xffff9b06809c]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x248f28)[0xffff9b065f28]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x2490ec)[0xffff9b0660ec]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x249660)[0xffff9b066660]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x1d1380)[0xffff9afee380]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x1d4f1c)[0xffff9aff1f1c]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN12QQmlDataBlob7tryDoneEv+0x54)[0xffff9afe6298]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader13setCachedUnitEP12QQmlDataBlobPKN3QV412CompiledData4UnitE+0xc0)[0xffff9b028aa0]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader6doLoadI12CachedLoaderEEvRKT_P12QQmlDataBlobNS_4ModeE+0x50)[0xffff9b02cb9c]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader18loadWithCachedUnitEP12QQmlDataBlobPKN3QV412CompiledData4UnitENS_4ModeE+0x2c)[0xffff9b028b04]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader7getTypeERK4QUrlNS_4ModeE+0x170)[0xffff9b02ad28]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x1d3f80)[0xffff9aff0f80]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x1d5a10)[0xffff9aff2a10]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader13setCachedUnitEP12QQmlDataBlobPKN3QV412CompiledData4UnitE+0x90)[0xffff9b028a70]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader6doLoadI12CachedLoaderEEvRKT_P12QQmlDataBlobNS_4ModeE+0x50)[0xffff9b02cb9c]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader18loadWithCachedUnitEP12QQmlDataBlobPKN3QV412CompiledData4UnitENS_4ModeE+0x2c)[0xffff9b028b04]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader7getTypeERK4QUrlNS_4ModeE+0x170)[0xffff9b02ad28]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x1d3f80)[0xffff9aff0f80]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x1d5a10)[0xffff9aff2a10]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader13setCachedUnitEP12QQmlDataBlobPKN3QV412CompiledData4UnitE+0x90)[0xffff9b028a70]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader6doLoadI12CachedLoaderEEvRKT_P12QQmlDataBlobNS_4ModeE+0x50)[0xffff9b02cb9c]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader18loadWithCachedUnitEP12QQmlDataBlobPKN3QV412CompiledData4UnitENS_4ModeE+0x2c)[0xffff9b028b04]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader7getTypeERK4QUrlNS_4ModeE+0x170)[0xffff9b02ad28]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x1d3f80)[0xffff9aff0f80]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x1d5a10)[0xffff9aff2a10]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader13setCachedUnitEP12QQmlDataBlobPKN3QV412CompiledData4UnitE+0x90)[0xffff9b028a70]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x1dbca8)[0xffff9aff8ca8]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x25e350)[0xffff9b07b350]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x25e5dc)[0xffff9b07b5dc]
/usr/lib/aarch64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x5c)[0xffff9a7797d8]
/usr/lib/aarch64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0xe4)[0xffff99d27a60]
/usr/lib/aarch64-linux-gnu/libQt5Core.so.5(_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData+0x274)[0xffff99d284d4]
/usr/lib/aarch64-linux-gnu/libQt5Core.so.5(+0x25350c)[0xffff99d6550c]
/usr/lib/aarch64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x254)[0xffff9ac386b8]
/usr/lib/aarch64-linux-gnu/libglib-2.0.so.0(+0x57948)[0xffff9ac38948]
/usr/lib/aarch64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x34)[0xffff9ac38a14]
/usr/lib/aarch64-linux-gnu/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x50)[0xffff99d65034]
/usr/lib/aarch64-linux-gnu/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x208)[0xffff99d247c8]
/usr/lib/aarch64-linux-gnu/libQt5Core.so.5(_ZN7QThread4execEv+0x9c)[0xffff99bdeea4]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x25dd28)[0xffff9b07ad28]
/usr/lib/aarch64-linux-gnu/libQt5Core.so.5(+0xce0ec)[0xffff99be00ec]
/usr/lib/aarch64-linux-gnu/libpthread.so.0(+0x6ff8)[0xffff995e2ff8]
/usr/lib/aarch64-linux-gnu/libc.so.6(+0xd32dc)[0xffff995332dc]
Error: signal 6:
nheko(+0x3af7b0)[0xaaaaac2df7b0]
linux-vdso.so.1(__kernel_rt_sigreturn+0x0)[0xffff9bc1c7dc]
/usr/lib/aarch64-linux-gnu/libpthread.so.0(raise+0xb8)[0xffff995ee1c8]
nheko(+0x3af848)[0xaaaaac2df848]
linux-vdso.so.1(__kernel_rt_sigreturn+0x0)[0xffff9bc1c7dc]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZNK17QQmlPropertyCache8propertyEi+0x10)[0xffff9aff2c74]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x24ae00)[0xffff9b067e00]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x24b09c)[0xffff9b06809c]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x248f28)[0xffff9b065f28]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x2490ec)[0xffff9b0660ec]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x249660)[0xffff9b066660]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x1d1380)[0xffff9afee380]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x1d4f1c)[0xffff9aff1f1c]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN12QQmlDataBlob7tryDoneEv+0x54)[0xffff9afe6298]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader13setCachedUnitEP12QQmlDataBlobPKN3QV412CompiledData4UnitE+0xc0)[0xffff9b028aa0]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader6doLoadI12CachedLoaderEEvRKT_P12QQmlDataBlobNS_4ModeE+0x50)[0xffff9b02cb9c]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader18loadWithCachedUnitEP12QQmlDataBlobPKN3QV412CompiledData4UnitENS_4ModeE+0x2c)[0xffff9b028b04]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader7getTypeERK4QUrlNS_4ModeE+0x170)[0xffff9b02ad28]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x1d3f80)[0xffff9aff0f80]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x1d5a10)[0xffff9aff2a10]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader13setCachedUnitEP12QQmlDataBlobPKN3QV412CompiledData4UnitE+0x90)[0xffff9b028a70]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader6doLoadI12CachedLoaderEEvRKT_P12QQmlDataBlobNS_4ModeE+0x50)[0xffff9b02cb9c]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader18loadWithCachedUnitEP12QQmlDataBlobPKN3QV412CompiledData4UnitENS_4ModeE+0x2c)[0xffff9b028b04]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader7getTypeERK4QUrlNS_4ModeE+0x170)[0xffff9b02ad28]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x1d3f80)[0xffff9aff0f80]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x1d5a10)[0xffff9aff2a10]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader13setCachedUnitEP12QQmlDataBlobPKN3QV412CompiledData4UnitE+0x90)[0xffff9b028a70]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader6doLoadI12CachedLoaderEEvRKT_P12QQmlDataBlobNS_4ModeE+0x50)[0xffff9b02cb9c]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader18loadWithCachedUnitEP12QQmlDataBlobPKN3QV412CompiledData4UnitENS_4ModeE+0x2c)[0xffff9b028b04]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader7getTypeERK4QUrlNS_4ModeE+0x170)[0xffff9b02ad28]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x1d3f80)[0xffff9aff0f80]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x1d5a10)[0xffff9aff2a10]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(_ZN14QQmlTypeLoader13setCachedUnitEP12QQmlDataBlobPKN3QV412CompiledData4UnitE+0x90)[0xffff9b028a70]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x1dbca8)[0xffff9aff8ca8]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x25e350)[0xffff9b07b350]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x25e5dc)[0xffff9b07b5dc]
/usr/lib/aarch64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x5c)[0xffff9a7797d8]
/usr/lib/aarch64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0xe4)[0xffff99d27a60]
/usr/lib/aarch64-linux-gnu/libQt5Core.so.5(_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData+0x274)[0xffff99d284d4]
/usr/lib/aarch64-linux-gnu/libQt5Core.so.5(+0x25350c)[0xffff99d6550c]
/usr/lib/aarch64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x254)[0xffff9ac386b8]
/usr/lib/aarch64-linux-gnu/libglib-2.0.so.0(+0x57948)[0xffff9ac38948]
/usr/lib/aarch64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x34)[0xffff9ac38a14]
/usr/lib/aarch64-linux-gnu/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x50)[0xffff99d65034]
/usr/lib/aarch64-linux-gnu/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x208)[0xffff99d247c8]
/usr/lib/aarch64-linux-gnu/libQt5Core.so.5(_ZN7QThread4execEv+0x9c)[0xffff99bdeea4]
/usr/lib/aarch64-linux-gnu/libQt5Qml.so.5(+0x25dd28)[0xffff9b07ad28]
/usr/lib/aarch64-linux-gnu/libQt5Core.so.5(+0xce0ec)[0xffff99be00ec]
/usr/lib/aarch64-linux-gnu/libpthread.so.0(+0x6ff8)[0xffff995e2ff8]
/usr/lib/aarch64-linux-gnu/libc.so.6(+0xd32dc)[0xffff995332dc]
`

**Comment by deepbluev7** [comment] 2021-11-25 20:21
Did you update from 0.9.0 to 0.9.0 or from 0.8.2 to 0.9.0?

**Comment by nebocamin** [comment] 2021-11-25 20:50
from 0.9.0 to 0.9.0 i had the forever turning dots. but wait... here i had a --delete-data first and then fresh install

**Comment by deepbluev7** [comment] 2021-11-25 20:51
So it wasn't working before and now it doesn't work either?

**Comment by alistair23** [comment] 2021-11-25 22:37
Same problem here. Was seeing the infinite spin issue with the 0.9.0 and since the update to the latest nightly I see a segfault on startup.

The backtrace is:

```
#0  0x0000fffff73cac74 in QQmlPropertyCache::property(int) const () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#1  0x0000fffff743fe00 in  () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#2  0x0000fffff744009c in  () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#3  0x0000fffff743df28 in  () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#4  0x0000fffff743e0ec in  () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#5  0x0000fffff743e660 in  () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#6  0x0000fffff73c6380 in  () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#7  0x0000fffff73c9f1c in  () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#8  0x0000fffff73be298 in QQmlDataBlob::tryDone() () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#9  0x0000fffff7400aa0 in QQmlTypeLoader::setCachedUnit(QQmlDataBlob*, QV4::CompiledData::Unit const*) () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#10 0x0000fffff7404b9c in void QQmlTypeLoader::doLoad<CachedLoader>(CachedLoader const&, QQmlDataBlob*, QQmlTypeLoader::Mode) ()
    at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#11 0x0000fffff7400b04 in QQmlTypeLoader::loadWithCachedUnit(QQmlDataBlob*, QV4::CompiledData::Unit const*, QQmlTypeLoader::Mode) ()
    at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#12 0x0000fffff7402d28 in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#13 0x0000fffff73c8f80 in  () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#14 0x0000fffff73caa10 in  () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#15 0x0000fffff7400a70 in QQmlTypeLoader::setCachedUnit(QQmlDataBlob*, QV4::CompiledData::Unit const*) () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#16 0x0000fffff7404b9c in void QQmlTypeLoader::doLoad<CachedLoader>(CachedLoader const&, QQmlDataBlob*, QQmlTypeLoader::Mode) ()
    at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#17 0x0000fffff7400b04 in QQmlTypeLoader::loadWithCachedUnit(QQmlDataBlob*, QV4::CompiledData::Unit const*, QQmlTypeLoader::Mode) ()
    at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#18 0x0000fffff7402d28 in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#19 0x0000fffff73c8f80 in  () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#20 0x0000fffff73caa10 in  () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#21 0x0000fffff7400a70 in QQmlTypeLoader::setCachedUnit(QQmlDataBlob*, QV4::CompiledData::Unit const*) () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#22 0x0000fffff7404b9c in void QQmlTypeLoader::doLoad<CachedLoader>(CachedLoader const&, QQmlDataBlob*, QQmlTypeLoader::Mode) ()
    at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#23 0x0000fffff7400b04 in QQmlTypeLoader::loadWithCachedUnit(QQmlDataBlob*, QV4::CompiledData::Unit const*, QQmlTypeLoader::Mode) ()
    at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#24 0x0000fffff7402d28 in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#25 0x0000fffff73c8f80 in  () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#26 0x0000fffff73caa10 in  () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#27 0x0000fffff7400a70 in QQmlTypeLoader::setCachedUnit(QQmlDataBlob*, QV4::CompiledData::Unit const*) () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#28 0x0000fffff73d0ca8 in  () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#29 0x0000fffff7453350 in  () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#30 0x0000fffff74535dc in  () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#31 0x0000fffff6b517d8 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/aarch64-linux-gnu/libQt5Widgets.so.5
#32 0x0000fffff60ffa60 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/aarch64-linux-gnu/libQt5Core.so.5
#33 0x0000fffff61004d4 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/aarch64-linux-gnu/libQt5Core.so.5
#34 0x0000fffff613d50c in  () at /usr/lib/aarch64-linux-gnu/libQt5Core.so.5
#35 0x0000fffff70106b8 in g_main_context_dispatch () at /usr/lib/aarch64-linux-gnu/libglib-2.0.so.0
#36 0x0000fffff7010948 in g_main_context_iterate.constprop () at /usr/lib/aarch64-linux-gnu/libglib-2.0.so.0
#37 0x0000fffff7010a14 in g_main_context_iteration () at /usr/lib/aarch64-linux-gnu/libglib-2.0.so.0
#38 0x0000fffff613d034 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/aarch64-linux-gnu/libQt5Core.so.5
#39 0x0000fffff60fc7c8 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/aarch64-linux-gnu/libQt5Core.so.5
#40 0x0000fffff5fb6ea4 in QThread::exec() () at /usr/lib/aarch64-linux-gnu/libQt5Core.so.5
#41 0x0000fffff7452d28 in  () at /usr/lib/aarch64-linux-gnu/libQt5Qml.so.5
#42 0x0000fffff5fb80ec in  () at /usr/lib/aarch64-linux-gnu/libQt5Core.so.5
#43 0x0000fffff59baff8 in start_thread () at /usr/lib/aarch64-linux-gnu/libpthread.so.0
#44 0x0000fffff590b2dc in thread_start () at /usr/lib/aarch64-linux-gnu/libc.so.6
```

**Comment by deepbluev7** [comment] 2021-11-25 22:39
can you install the debug package, so that I can get some actual symbols? Alternatively, you might want to try wiping your qmlcache in `~/.var/app/io.github.NhekoReborn.Nheko/cache/nheko/nheko/`

**Comment by alistair23** [comment] 2021-11-25 22:42
`io.github.NhekoReborn.Nheko.Debug/aarch64/master` is already installed, is there a different one I should install?

Tried deleting that, no difference

**Comment by deepbluev7** [comment] 2021-11-25 23:08
Hm, I had hoped that would provide a more readable backtrace, but I guess not...

**Comment by deepbluev7** [comment] 2021-11-27 01:46
@alistair23 , your crash should be fixed

**Comment by deepbluev7** [comment] 2021-11-27 01:57
I think I fixed most issues in here. Anything I forgot, please reopen in a separate issue, because I am a bit lost. Thank you!

**Closed by deepbluev7** 2021-11-27 01:57 UTC
Labels: bug, secrets-service
