### ISSUE TITLE
[Qt6, Wayland] Crash when mouse is changed to hand 

### ISSUE THREAD

**Issue by TheSunCat** [Nheko-Reborn/nheko#1481] opened 2023-06-09 14:28 UTC
### Describe the bug

After updating nheko to the latest git, it launches fine, but hovering over the logout button or a link causes it to crash shortly after.

### To Reproduce

1. Hover over a link (or anything that causes the hand cursor to be set)
2. Wait less than a second
3. Observe crash

### What happened?

Nheko crashes

### Expected behavior

Nheko does not crash

### Version

0.11.3.2-2eccec66

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

Hyprland (Wayland)

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
Error sending request: Resource temporarily unavailable
[2023-06-09 16:27:37.493] [qml] [warning] The Wayland connection experienced a fatal error: Resource temporarily unavailable (:0, )
```

**Comment by nico-famedly** [comment] 2023-06-09 14:36
Does maybe your compositor bork on the cursor icon? Is there anything interesting in the compositor logs?

**Comment by TheSunCat** [comment] 2023-06-09 14:40
This is what Hyprland prints when nheko crashes:
```ini
[LOG] Window 559c5a1e8b20 unmapped (class nheko)
[LOG] Unregistered late callbacks XDG
[LOG] Callback 559c5a1e8b48 -> 559c5a1e8b40, XDG Window Late removed.
[LOG] Callback 559c5a1e8ce8 -> 559c5a1e8ce0, XDG Window Late removed.
[LOG] Callback 559c5a1e8e20 -> 559c5a1e8e18, XDG Window Late removed.
[LOG] Callback 559c5a1e8f58 -> 559c5a1e8f50, XDG Window Late removed.
[LOG] Callback 559c5a1e8ef0 -> 559c5a1e8ee8, XDG Window Late removed.
[LOG] Callback 559c5a1e8e88 -> 559c5a1e8e80, XDG Window Late removed.
[LOG] Callback 559c5a1e8fc0 -> 559c5a1e8fb8, XDG Window Late removed.
[LOG] Callback 559c5a1e8db8 -> 559c5a1e8db0, XDG Window Late removed.
[LOG] Framebuffer created, status 36053
[LOG] On closed window, new focused candidate is 559c5a1d97b0
[LOG] Set keyboard focus to surface 559c59eda200, with window name: foot
[LOG] Destroying the SubSurface tree of unmapped window 559c5a1e8b20
[LOG] Callback 559c5a1df328 -> 559c5a1df320, SurfaceTreeNode removed.
[LOG] Callback 559c5a1df390 -> 559c5a1df388, SurfaceTreeNode removed.
[LOG] Callback 559c5a1df2c0 -> 559c5a1df2b8, SurfaceTreeNode removed.
[LOG] SurfaceTree Node removed
[LOG] Callback 559c5a1e9160 -> 559c5a1e9158, Toplevel removed.
[LOG] Callback 559c5a1e90f8 -> 559c5a1e90f0, Toplevel removed.
[LOG] Callback 559c5a1e91c8 -> 559c5a1e91c0, Toplevel removed.
[LOG] Callback 559c5a1e9370 -> 559c5a1e9368, CWLSurface removed.
[LOG] CWLSurface 559c5a1e9340 called destroy()
[LOG] Callback 559c5a1e8c18 -> 559c5a1e8c10, CWindow removed.
[LOG] Window 559c5a1e8b20 destroyed, queueing. (class )
[LOG] Callback 559c5a1e8bb0 -> 559c5a1e8ba8, XDG Window removed.
[LOG] Callback 559c5a1e8c80 -> 559c5a1e8c78, XDG Window removed.
[ERR] onWindowRemovedTiling node null?
[LOG] Callback 559c5a1427d8 -> 559c5a1427d0, textInput removed.
[LOG] Callback 559c5a142770 -> 559c5a142768, textInput removed.
[LOG] Callback 559c5a142708 -> 559c5a142700, textInput removed.
[LOG] Callback 559c5a1426a0 -> 559c5a142698, textInput removed.
[LOG] Cleanup: destroyed a window
[LOG] Set keyboard focus to surface 559c59f39070, with window name: foot
```
The `onWindowRemovedTiling` error seems to be printed for all windows, so I do not think it's related. Going to test on Sway, will edit this post with an update in a minute.

**Comment by deepbluev7** [comment] 2023-06-09 20:54
Shouldn't the interesting line be before the unmapped?

**Comment by q234rty** [comment] 2023-06-10 09:26
Can't reproduce on latest hyprland with fractional scaling, could you maybe run nheko with `WAYLAND_DEBUG=1`, reproduce the crash and attach the stderr?

**Comment by TheSunCat** [comment] 2023-06-10 18:45
Sure thing, here's the crash with WAYLAND_DEBUG set: 
[error.log](https://github.com/Nheko-Reborn/nheko/files/11713083/error.log)

**Comment by TheSunCat** [comment] 2023-06-10 18:59
@q234rty helped me get sway-git installed and I can confirm it happens on Sway too (I was originally testing with the non-git Sway package). So this is likely an issue with all wlroots compositors, not just Hyprland.

**Comment by vaxerski** [comment] 2023-06-12 14:41
this got fixed in wlroots, I'll update the dep in hyprland when I get the chance.

This can be closed

**Comment by TheSunCat** [comment] 2023-06-12 15:07
Great, thank you! I'll keep it open just in case until I can verify it no longer happens on my machine (once hyprland-git gets the wlroots update).

**Closed** 2023-06-12 23:08 UTC
Labels: bug
