### ISSUE TITLE
Can't paste password into password field

### ISSUE THREAD

**Issue by audunmg** [Nheko-Reborn/nheko#119] opened 2020-02-16 10:57 UTC
### System:

- Nheko version: 
- Installation method: 
- Operating System:
- Qt version: 
- C++ compiler: 
- Desktop Environment: 

### Actual behavior
Password field pasting is disabled

### Expected behavior
Able to paste

### Steps to reproduce
Start application fresh, go to login or registration and attempt to paste password in passord fields

**Comment by adasauce** [comment] 2020-02-16 13:38
I just ran a test, and I'm able to paste passwords on the login screen. both via keyboard shortcut and right click context menu.

What version of nheko are you running? what OS / device?

**Comment by audunmg** [comment] 2020-02-18 14:37
Hello! 

Sorry for the lack of information, I'm running on a laptop, Fedora 31

I have tried digging through the sources of nheko and I'm starting to believe it's a problem with my QT libraries, not with nheko.

I haven't seen this issue in other QT apps, but since it only seems to be an issue for me, it must be a local problem on my end.

**Comment by deepbluev7** [comment] 2020-03-30 19:51
Thanks for the response (although I kinda missed it...). Since you say this seems to be a problem on your end, I will close this for now. If you can find a way to easily reproduce it, you can reopen this and I'll try to fix it :D

**Closed by deepbluev7** 2020-03-30 19:51 UTC
Labels: bug, info needed
