### ISSUE TITLE
Allow Multiple Accounts to Login

### ISSUE THREAD

**Issue by cfitz25** [Nheko-Reborn/nheko#592] opened 2021-05-26 03:06 UTC
Is it possible to allow for multiple accounts to login at once?
I feel that would be quite useful for some people.

**Comment by deepbluev7** [comment] 2021-05-26 10:01
You currently need to use different profiles, by starting Nheko from the command line with `--profile <profilename>`. This will however open multiple windows.

**Comment by pymq** [comment] 2021-06-06 11:11
Seems like a duplicate of #489.

**Comment by deepbluev7** [comment] 2021-06-06 17:09
Closing in favour of #489

**Closed by deepbluev7** 2021-06-06 17:09 UTC
Labels: enhancement
