### ISSUE TITLE
Font in chat with line break

### ISSUE THREAD

**Issue by derNonus** [Nheko-Reborn/nheko#490] opened 2021-02-23 14:51 UTC
### Describe the bug
An unwanted line break occurs in all of my chats
### Screenshots
![Screenshot_2021-02-23_15-45-56](https://user-images.githubusercontent.com/47027824/108860341-64e00000-75ee-11eb-915c-370c9bcea2c3.png)

### System:

- Nheko version: 0.8.1-865344c7
- Profile used: 
- Installation method: aur git-version
- Operating System: Archlinux
- Desktop Environment: KDE

**Comment by deepbluev7** [comment] 2021-03-14 02:00
Did you make your window super narrow or is the row width calculation just horribly broken? Do you have some logs?

**Comment by deepbluev7** [comment] 2021-07-13 00:54
Since no info was provided and this affects an old version, I will close this, because I can't reproduce it.

**Closed by deepbluev7** 2021-07-13 00:54 UTC
Labels: bug, info needed
