### ISSUE TITLE
THE LOADING TAKES FOREVER.

### ISSUE THREAD

**Issue by sombrebombre** [Nheko-Reborn/nheko#1836] opened 2024-10-27 11:39 UTC
### Describe the bug

The bug occurs when I use the application.

It's always loading forever, i don't understand why because i have a really good wifi. But, the wifi can still work in order for me to see the icons of different communities even if It's extremely slow.

### To Reproduce

1. Open the client
2. Create an account

### What happened?

The application just started loading forever, after I created an account, on the right side where i'm supposed to see the messages.

### Expected behavior

I expected the client to not load for so long and to be fluid while using it.

### Screenshots

![load](https://github.com/user-attachments/assets/d0e50fe0-95e0-4177-b668-0bb4070e6295)
![j](https://github.com/user-attachments/assets/84703b90-31bf-4425-ba29-3e82f2666750)
![what](https://github.com/user-attachments/assets/d1173931-25d0-4574-92bc-966766670272)

### Version

0.12.0

### Operating system

Windows

### Installation method

Windows download

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment] 2024-10-30 01:07
Usually this means that your server is slow in serving the initial sync response, not your wifi or Nheko. After the initial load Nheko should be fast-ish, but the initial load takes longer because we request more data from the server than other clients.

Duplicate of #141

**Closed by deepbluev7** 2024-10-30 01:07 UTC
Labels: bug
