### ISSUE TITLE
Insane settings scrolling with touchpad

### ISSUE THREAD

**Issue by hiiamboris** [Nheko-Reborn/nheko#1364] opened 2023-02-14 10:44 UTC
### Describe the bug

Using touchpad on W10.
While chat log scroll works fine: I can even scroll it by a few pixels, a smallest scroll attempt in the User Settings window scrolls all the way to the bottom/top.

### To Reproduce

Just scroll settings by touchpad gesture.

### Version

0.11.1-02b900f8

### Operating system

Windows

### Installation method

Windows download

### Did you use profiles?

- [ ] Profiles used?

**Comment by LorenDB** [comment] 2023-02-14 19:45
Can reproduce on Windows 11. This only affects the app settings page. It seems to have to do with kinetic scrolling.

**Comment by LorenDB** [comment] 2023-03-01 23:02
This seems to be a Windows-specific bug, as I cannot reproduce on Linux.

**Comment by LorenDB** [comment] 2023-03-01 23:13
Related: https://bugreports.qt.io/browse/QTBUG-56075

This should be fixed once we get a release out that is built against Qt 5.15.8

**Comment by deepbluev7** [comment] 2023-06-08 21:42
This should be better on Qt6 now, but scrolling there is still a bit weird. Qt6.6 should fix that though.

**Closed by deepbluev7** 2023-06-08 21:42 UTC
Labels: bug, upstream issue
