### ISSUE TITLE
Syntac highlighting in code blocks

### ISSUE THREAD

**Issue by auroraanna** [Nheko-Reborn/nheko#1227] opened 2022-11-12 19:58 UTC
### The Problem

I kind of miss the syntax highlighting in code blocks from Schildichat (Element too?).

### The Solution

Add syntax highlighting to code blocks in nheko.

### Alternatives

- Opening code blocks in external editors with syntax highlighting
- Switching clients

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by LorenDB** [comment] 2022-11-13 13:36
Duplicate of #248

**Closed** 2022-11-13 13:36 UTC
Labels: enhancement
