### ISSUE TITLE
Better Linux Mobile (PinePhone) compatibility

### ISSUE THREAD

**Issue by xthe3dmanx** [Nheko-Reborn/nheko#469] opened 2021-02-09 16:29 UTC
**Is your feature request related to a problem? Please describe.**
The current app builds, installs, and partially runs on the PinePhone (Tested on Arch with Phosh). It is even responsive and displays extremely well on the small screen. I was able to login and get into rooms, however that is as far as I am able to get. The app begins to lock up when scrolling through messages or while switching rooms. These lock ups are only with the app itself and do not cause a whole system freeze. Sometimes the app will turn the whole window all black or weird colored boxes. This app is a good start and could be the best matrix client on the PinePhone or Librem if the lockups get fixed.

**Describe the solution you'd like**
Updates to fix lockup issues on Linux Mobile

**Additional context**
If these lockups were fixed, I could see this as becoming the most popular client on Linux Mobile. visually and feature wise it looks great. It is better visually than all the other Matrix clients I tried.

**Comment by redsky17** [comment] 2021-03-27 21:59
Are you running the binary directly or via flatpak?  I haven't used Arch w/ Phosh yet, but I have not experience these issues on either manjaro w/ Plasma Mobile or Mobian w/ phosh.

**Comment by xthe3dmanx** [comment] 2021-03-28 02:25
I have tried the flatpak, the AUR binary and also built directly from git. Had the same issue on all. When trying to scroll through messages it locks up for a bit, then will scroll a few messages before locking up again. Trying to switch rooms causes some weird blue screen and graphical glitches as well. The lock ups are slightly fewer on the flatpak version, but the room switching blue screen happens on all versions. I have tried on 2 separate PinePhones one with Arch Phosh and one with Arch Plasma and get the same result on both.


![Error](https://user-images.githubusercontent.com/67486856/112740340-d4287700-8f41-11eb-82f6-04256b46907c.jpg)
.

**Comment by deepbluev7** [comment] 2021-06-30 20:36
This should be improved by a bit now. What is still missing is disabling the hover effects on touch as well as improving performance.

**Comment by Bugsbane** [comment] 2021-08-11 04:40
Overall, it's surprisingly usable. I'm actually really happy with Nheko, so thank you!

I thought I'd leave a couple of usability suggestions, based on the flatpak on Manjaro+PlaMo. I want to stress that these are all generally small things that would enhance usability. That said I feel like Nheko is already the best and most usable option on mobile Linux, so these are all intended not as criticisms, but enhancement suggestions. What you've made is already amazing! My intention is to help Nheko on mobile Linux to go from being the best, to being simply amazing :):

### Loading screen:
1. The screen background colour is set to the same background colour as the logo's circle, making the two blend together. The circle logo could be made to stand out better with a slightly lighter screen background color. Alternatively, get rid of the circle, as the main logo already contrasts nicely with the screen backgound.

### Notifications:
1. Notifications for chats in all subscribed rooms show when the user is in the app, covering over the actual messages the user is looking at in the app itself. Part of this is the behavior of displaying notifications in PlaMo itself, but I would suggest only sending notifications when Nheko isn't currently the foreground app, or at the very least not sending notifications for the room they're viewing. Having the notification for a message, cover the message itself in Nheko is less desirable to the user than just seeing the message in the app.

### Login screen:
1. Looks nice! Happy that SSO worked, too...

### List of rooms screen:
1. Overall works well. The top part with the current user account though looks very similar to the list of rooms underneath and it's easy to mistake the user as just another room. I'd suggest making the background a slightly lighter (or darker) shade to differentiate it from the list of rooms below.
2. At the moment single tapping on a room just hilghts the room name and double tapping is required to enter the room. I suggest changing it so that entering a room is just a single tap as it's more discoverable.

### Settings screen:
1. The whole screen exceeds the screen width and goes of the right hand edge of the screen.
2. It also uses an unnecessary scroll bar (which covers more of the right hand side of the screen screen).
3. Touch mode can be manually enabled but defaults to off, even on a mobile device with a small screen. Automatically turning this mode on when the screen is either small or much taller than wide would go a long way to making the app more intuitive when a user first opens it on a mobile device.

### Rooms discussion screen:
1. The time displayed on the right uses 50% of the width of the horizontal space available for the messages themselves, and even more if one of them has the "edited" pencil icon. Meanwhile there is a large, empty column on the left under the avatars. You could give 50% more space to the actual messages just by making the time slightly smaller and putting it in the empty column to the left of the message, instead of to the right. I would suggest making it a slightly darker color than the messages as well, as this info is less key than the messages themselves. Making it the same brightness distracts from the messages. The "edited" pencil icon can be made smaller and put to the right of the time.
2. Trying to scroll with touch works over the avatar column. When trying to scroll over the message or time columns (3/4 of the screen) it selects text instead which is a much less commonly needed action than scrolling through the messages. I would enable text selection only on a long press over a word, using scrolling any other time.
3. The room topic extends slightly off the right hand side of the screen.
4. The extra indentation for the message, compared to the poster name isn't needed for readability (you already have good separation there), but reduces the available width for the messages. I'd just remove it and left align the messages to the same left border as the poster name.
5. When first opening the room, the message posting field is automatically given focus, which prompts the onscreen keyboard to come up, covering nearly half the screenspace available to the messages. If you avoid giving it focus until the user taps on the message entry field, then almost twice as many messages can be displayed when first entering the room.

### Room details display screen:
1. Extends of the right hand side of the screen
2. It's not clear how to go back to the previous screen. In practice, the user can use the "X" button at the bottom in Plasma Mobile, however this frequently closes apps in Plasma Mobile, so without a clear indication, the user is left in a situation where the action needed to go back could potentially close the app. This could be avoided just by providing a "< Back" button at the top left of the screen.

**Comment by maltee1** [comment] 2022-01-27 20:23
I just tried nheko on my new pinephone pro. It looks great, but it's a bit rough around the edges.
@Bugsbane summarized almost everything I noticed. I have a few things to add:
### Rooms discussion screen
Metadata should be displayed in the last row of a message rather than a separate column, flushed right, with smaller size than the rest of the text (possibly in gray) - at least if the screen/window is narrow. This is how most modern messaging apps handle it and I think it's best practice because it doesn't use additional space.
Message bubbles would greatly improve legibility and space use. I know they are controversial, but there's a reason all major apps use them. They provide author information by color and position (right for oneself and left for everyone else). In a DM, which is the majority of chats for most people, you wouldn't need author names or avatars at all because you have them on top and the bubbles make a clear distinction between your own messages and those of the person you're talking to.
Sliding sideways to return to the room list is nice, but it's very sensitive. I accidentally go back to the room list when scrolling vertically a lot. I'm not sure if this is an issue in Qt. I also think that sideways slide is a good way to initiate message actions (reply, forward) rather than changing screens.
### VoIP
Only works partially. I couldn't get video calls to work, but that may be due to driver issues on the rather new hardware. I haven't yet been able to test the camera with any other app.
Outgoing voice calls work, but output selection (earpiece or speaker) doesn't seem to work in nheko.
Incoming calls don't work. The phone rings (again, nheko doesn't select the right output), but there's nowhere to pick up.
### Popup windows
Popup windows e.g. for user information don't work well on mobile. I'm not sure if this is an issue that should be fixed on the window manager side or on the application side. However, if nheko didn't open any additional windows, there wouldn't be an issue.

**Comment by maltee1** [comment] 2022-02-25 15:15
This is why incoming calls don't work: Why would the call popup be disabled in mobile mode?
visible: CallManager.haveCallInvite && !Settings.mobileMode

**Comment by deepbluev7** [comment] 2022-02-25 15:16
There should be a fullscreen call page instead. I hope I didn't delete that by accident at some point.

**Comment by maltee1** [comment] 2022-02-25 15:18
Probably not. Fullscreen windows don't seem to work for me in general, which is most likely the reason I can't see it. I haven't filed a bug yet, because I don't know if this is an issue in kwin. I should probably file one anyway

**Comment by deepbluev7** [comment] 2022-02-25 15:58
It is not a window, it is a full window overlay over the chat (instead of a bar at the bottom)

**Comment by deepbluev7** [comment] 2022-02-25 16:02
Here is a gif of how it looks like: https://fosstodon.org/web/@deepbluev7/105839965698434981

**Comment by maltee1** [comment] 2022-02-25 16:06
That looks pretty nice, I'd like to have that ;)
I get nothing other than the message that the user has placed a call. If I disable touchscreen mode, I get that bar on the bottom and I can pick up the call, so voip is definitely working.

**Comment by deepbluev7** [comment] 2022-02-25 16:07
Yeah, that looks like that popup broke then. It might just fail to open though.

**Comment by deepbluev7** [comment] 2022-02-25 16:09
I think the issue is that we renamed the thing used as the parent here: https://github.com/Nheko-Reborn/nheko/blob/master/resources/qml/Root.qml#L297

**Comment by maltee1** [comment] 2022-02-25 16:10
I actually think the call popup should not just show up in Nheko, but overlay anything anywhere, including the lockscreen.
But that's probably a bit more work.

**Comment by deepbluev7** [comment] 2022-02-25 16:10
Especially cross platform.

**Comment by maltee1** [comment] 2022-02-25 16:13
Maybe just a window that forces focus would be fairly simple? That'd be a major improvement already.

**Comment by deepbluev7** [comment] 2022-02-25 16:13
You mean like the current Image overlay?

**Comment by maltee1** [comment] 2022-02-25 16:14
well, it doesn't have to be fullscreen.

**Comment by deepbluev7** [comment] 2022-02-25 16:17
Forcing focus is not possible on Wayland

**Comment by maltee1** [comment] 2022-03-04 20:56
Most of the issues have probably been solved by now, maybe it's time to close this issue and open separate issues for each remaining task?

**Closed** 2022-03-04 23:42 UTC
Labels: enhancement, mobile, voip
