### ISSUE TITLE
Ability to hide joins/leaves (ideally per-room)

### ISSUE THREAD

**Issue by haasn** [Nheko-Reborn/nheko#588] opened 2021-05-22 08:20 UTC
**Is your feature request related to a problem? Please describe.**
Especially for large rooms, joins/leaves can get rather noisy, annoying and provide very little signal. Currently I can find no way to disable this functionality.

**Describe the solution you'd like**
The ability to disable whether or not to display joins and leaves. Ideally it should be possible to override this on a per-room basis, perhaps with the setting defaulting to "off" for sufficiently large rooms.

**Comment by deepbluev7** [comment] 2021-05-22 08:22
Duplicate of #411

**Closed by deepbluev7** 2021-05-22 08:22 UTC
Labels: enhancement
