### ISSUE TITLE
Not able to login without SSO

### ISSUE THREAD

**Issue by vbakc** [Nheko-Reborn/nheko#553] opened 2021-04-17 21:41 UTC
### Describe the bug
Not able to login without SSO.

### To Reproduce
1. Go to login screen
2. Fill Matrix ID

### Expected behavior
You enter a password and log in

### Actual behavior
Password field disappears

### Screenshots
![image](https://user-images.githubusercontent.com/30199803/115127312-3a9f3300-9fde-11eb-9cb7-0700379d6653.png)

### System:

- Nheko version: 0.7.2-3+b1
- Installation method: Debian repository (testing/bullseye)
- Operating System: Debian
- Desktop Environment: KDE Plasma

**Comment by deepbluev7** [comment] 2021-04-17 21:43
Duplicate of the pinned issue #487 .

**Closed by deepbluev7** 2021-04-17 21:43 UTC
Labels: bug
