### ISSUE TITLE
Can't disable or change notification sounds on macOS

### ISSUE THREAD

**Issue by snowkat** [Nheko-Reborn/nheko#1135] opened 2022-07-30 19:18 UTC
### Describe the bug

In System Preferences on macOS 12.5, there's no option to disable notification sounds for Nheko. This checkbox appears for other apps except for ones that control sounds via their own Preferences pane (ex., Mail.app).

This issue has been occurring in macOS 11.x and in previous versions of Nheko. I'm not sure if this is a macOS bug or an issue with how Nheko handles notifications on macOS. I don't believe this is a Qt-specific issue, because other Qt5 apps I'm using (Quassel and OBS) have the option to disable notification sounds in System Preferences.

### To Reproduce

1. Log into Nheko on macOS and make sure "Desktop Notifications" is enabled in Settings
2. When the "Allow notifications for Nheko?" notification appears, accept it
3. Enter System Preferences and go to "Notifications & Focus"
4. Find "Nheko" in the list of apps

### What happened?

The "Play sound for notifications" checkbox doesn't appear.

### Expected behavior

Either the "Play sound for notifications" checkbox appears, or the sound being played is controlled in the app.

### Screenshots

![nheko_missing_sound](https://user-images.githubusercontent.com/47487241/181945088-b03f2a45-fc87-4ee9-9d33-3d2cc9195654.png)

Using OBS as an example application that does show the checkbox.
![obs_show_sound](https://user-images.githubusercontent.com/47487241/181945287-6ef3ed7d-0624-4a10-84f3-ecae4a93ad2d.png)

### Version

0.10.0-7df260f5

### Operating system

macOS

### Installation method

macOS DMG file

### Did you use profiles?

- [ ] Profiles used?

**Comment by redsky17** [comment] 2022-08-04 02:17
I recently switched our codebase over to the new UserNotifications Framework ('new' as of 10.13 or so).  It's possible that I've missed some code somewhere in the creation of the `UNMutableNotificationContent`  (or related code) that relates to enabling the sound option.  Honestly, I'm not sure why using system-specified defaults wouldn't be... the default, but Apple is silly sometimes.  I can look into it more and will update.

**Comment by redsky17** [comment] 2022-08-04 02:21
A quick look at https://developer.apple.com/documentation/usernotifications/unmutablenotificationcontent/1649868-sound?language=objc suggests that I probably missed an option in the notification authorization code.  Should be an easy fix!

**Comment by redsky17** [comment] 2022-08-04 03:11
Hmm, actually, I double checked the code and I do ask for the sound during notification authorization.  Here's what my Nheko notification settings look like:

![Screen Shot 2022-08-03 at 11 07 04 PM](https://user-images.githubusercontent.com/962117/182754761-e47c561a-7de3-46de-8782-6de31eaea303.png)

I also confirmed that I get sounds when notifications come in.

Can you confirm how you installed nheko (I'm assuming via our GitHub Releases or similar?) Can you also share your notification settings that are *within* Nheko itself?  Maybe there's a discrepancy there (and maybe I should just remove those options entirely on macOS Nheko).

**Comment by snowkat** [comment] 2022-08-04 06:10
I originally had nheko installed via Homebrew (`brew install --cask nheko`), but moved to manually installing from GitHub Releases for some reason or another. I believe the cask just pulls from GitHub though.

I have "Alert on notification" disabled, but nothing else changes regarding sound if I enable it.
<img width="755" alt="image" src="https://user-images.githubusercontent.com/47487241/182773715-15772ae3-4a16-4a89-a280-55f94427157a.png">

**Comment by redsky17** [comment] 2022-08-04 16:01
Hmm... I'm kinda stumped at this point.  Apple's documentation on this isn't great (it's mostly geared towards development on iOS).  They also don't explain how code changes affect the results in the Notification Center.  From what I can gather, I have the code for requesting authorization for sound.  Your screenshot even shows this where it says 'Sounds, Banners' on the left.

I'll try installing the DMG on a fresh macOS VM to rule out any kind of configuration that somehow makes mine work vs yours that doesn't...  

I don't have a timeline for this since I'm not exactly sure what the issue is.  I spent several hours yesterday reading through Apple developer documentation as well as trying to search the internet for any similar issues.  The closest I got was some kind of bug with the Mail app that made the "Play Sound for notification" option disappear for some people on Big Sur, but I don't think that's related.  I'll keep poking and see what I can find.

**Comment by redsky17** [comment] 2022-08-04 20:32
I've been able to confirm the 'bad' behavior on a fresh Monterey VM:

![Screen Shot 2022-08-04 at 4 28 25 PM](https://user-images.githubusercontent.com/962117/182946910-86e999f8-6ede-45ce-a58a-532150d92121.png)

I don't know what's different about my system that causes it to have all of the correct options.

**Comment by redsky17** [comment] 2022-08-04 21:59
Hmm... It appears that when I add the `UNAuthorizationOptionBadges` flag to the request for notification permissions... the Notification Center displays *both* the sound checkbox and the badges checkbox.  This looks like a macOS bug to me...

When the current CI build finishes, would you mind testing out a nightly to see if it fixes the issue for you?

**Comment by deepbluev7** [comment] 2022-08-04 23:21
Works for me now! And I even have nice badge counts now!

**Comment by redsky17** [comment] 2022-08-04 23:23
In that case: closed via [213a28e](https://github.com/Nheko-Reborn/nheko/commit/213a28eee3954896190309b5150eb8931758390e)!

**Closed by redsky17** 2022-08-04 23:23 UTC
Labels: bug

**Comment by snowkat** [comment] 2022-08-05 00:39
Can confirm it worked here too. Thanks!
