### ISSUE TITLE
Newlines are removed when message is a reply

### ISSUE THREAD

**Issue by msrd0** [Nheko-Reborn/nheko#1343] opened 2023-01-31 16:46 UTC
### Describe the bug

Newlines are removed when message is a reply

### To Reproduce

1. Send a message
2. Have another user reply to that message with a message that contains two consecutive newlines

### What happened?

The message gets displayed without newlines

### Expected behavior

The message gets displayed with newlines

### Screenshots

**Nheko:**

![Screenshot_2023-01-31-17-44-09](https://user-images.githubusercontent.com/7853372/215825410-e121f519-4516-41a1-ae3e-5e3aad6c080e.png)

**Element:**

![image](https://user-images.githubusercontent.com/7853372/215826679-2373fba7-06bd-4605-a090-9336cdf5c66f.png)

### Version

0.11.1-f6b976b4

### Operating system

Linux

### Installation method

Local build

### Qt version

5.15.8+kde+r174-1

### C++ compiler

gcc version 12.2.1 20230111 (GCC)

### Desktop Environment

sway, xdg-desktop-portal-wlr, with XDG_CURRENT_DESKTOP=KDE env var

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment] 2023-01-31 16:48
Duplicate of #757

**Closed by deepbluev7** 2023-01-31 16:48 UTC
Labels: bug

**Comment by msrd0** [comment] 2023-01-31 16:53
Does #757 also track the removal of double newlines? I have verified that there are two `\n\n` in the source code of the event.

**Comment by deepbluev7** [comment] 2023-01-31 17:26
The double newlines are actually required, possibly not the double br, but they don't matter. It's reply fallbacks and required by the spec, iirc. You need an empty line between the reply content and the other content, which translates to 2 newlines.

**Comment by msrd0** [comment] 2023-01-31 17:32
You mean when writing html you need a double newline? Nheko doesn't actually render double newlines in html any different than any other whitespace. And at least the html spec does not require any actual `\n`'s for newlines, `<br/>` is sufficient.

Here's the entire message:

```html
<mx-reply><blockquote><a href='https://matrix.to/#/!FudtYTRSkeGVeWBQyo:msrd0.de/$asxZfvDZ6T6q3DfketqnmmkJJ0v4K37H59SQJweCeSo'>In reply to</a> <a href='https://matrix.to/#/@telegram_831271470:msrd0.de'>qsx (Telegram)</a><br/>Mensa Ahornstraße</blockquote></mx-reply><strong>Plan für Mensa Ahornstraße</strong> <br/><br/><em>Dienstag, 31.01.2023</em><br/><br/><em>Klassiker</em>  2,80 €<br/><strong>Schweineschnitzel</strong> | Pfeffersauce 🐷<br/><br/><em>Tellergericht vegetarisch</em>  2,00 €<br/><strong>Kürbis-Erbsen-Eintopf mit Curry</strong> | Fladenbrot 🌱🥑<br/><br/><em>Vegetarisch</em>  2,20 €<br/><strong>Kürbis-Chia-Taler</strong> | Orientalische Tomatensauce 🌱🥑<br/><br/>Hauptbeilagen  | Pommes Frites oder Penne Rigate <br/><br/>Nebenbeilage <strong>Fingermöhrchen oder Mischsalat</strong>
```

**Comment by deepbluev7** [comment] 2023-01-31 17:35
No, the body requires the `\n` after the reply. The reply is also why your line-breaks vanish in Nheko.

**Comment by msrd0** [comment] 2023-01-31 17:39
Are you sure? Element does not write a newline there (but it uses `<p>` instead of `<br/>` which does work in nheko)

**Comment by deepbluev7** [comment] 2023-01-31 17:44
Well, br tags not working is a separate issue. Can you try the current master branch, if it behaves as you expect?

Basically 2 spaces + newline creates a br tag in markdown, 2 newlines creates a paragraph, 1 newline usually creates nothing. In your message it looks like you uses 2 spaces + newline. Last release of nheko has a bug, where br tags don't work properly.

Making newlines generate br tags on its own is a new feature on master as is just fixing br tags and quite a few other changes. Part of your issue was that on its own messages that match the html exactly would be sent as plain text too, which was behaving inconsistently  when replying, since that forces markdown.

All in all you hit like 3 bugs at once or more, that have since been fixed, the biggest of them just being the newline behaviour in general. And one behaviour enforced by the spec interacting badly with the rest.

**Comment by msrd0** [comment] 2023-01-31 18:02
Yep, seems to be working on the master branch version :+1:
