### ISSUE TITLE
nheko starts to fluctuate/gets shaky when the application size is reduced to small

### ISSUE THREAD

**Issue by utkarsh2102** [Nheko-Reborn/nheko#603] opened 2021-06-07 12:19 UTC
### Describe the bug
If you start to decrease the size of nheko window, at a point you'll find the nheko starts to fluctuate and shaky.

### To Reproduce
1. Keep reducing the application window size.
2. See error

### Expected behavior
It shouldn't start to fluctuate or shake, just the size should reduce.

**Comment by deepbluev7** [comment] 2021-06-07 15:33
Could you record that? It's a bit hard to visualize :D

**Comment by deepbluev7** [comment] 2021-08-31 16:15
Can't reproduce and no further info was provided, so closing this. Feel free to reopen, if you can provide a video that demonstrates the issue or similar.

**Closed by deepbluev7** 2021-08-31 16:15 UTC
Labels: bug
