### ISSUE TITLE
UI/UX Hide lurker change messages (join/avatar/name messages)

### ISSUE THREAD

**Issue by kimcosmos** [Nheko-Reborn/nheko#897] opened 2022-01-16 05:52 UTC
### The Problem

Many groups get a lot of visitors but few messages. People sticking their head in to see what's been said.  (90% of what's said is changes to join/avatar/name)

### The Solution

A Show 'past member status messages' option on each group, with the default set to Hidden... past being 1 hour ago.
Suddenly, low activity groups have enough real content that they can become live chat forums. Slow groups become instantly readable without endless scrolling. Unhide and search user if you need to check they are the same person.

### Alternatives

In element (or Schildi) you can click HIDE UserName>All settings>Preferences>Timeline Join, Avatar, Name
Global view filters for status message types, like element has, are far better than nothing.

### Additional context

Many possibilities, whatever's easiest to code given the framework

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment] 2022-01-16 15:38
Duplicate of #411 and there is a pr #891

**Closed by deepbluev7** 2022-01-16 15:38 UTC
Labels: enhancement
