### ISSUE TITLE
Can't get voice calls / VOIP to work

### ISSUE THREAD

**Issue by vertigo220** [Nheko-Reborn/nheko#1286] opened 2023-01-14 07:06 UTC
### Describe the bug

Tested this with a friend and neither of us could even find an option for voice. He was convinced it doesn't have the capability, but I knew I saw it did, and looked again and it's listed as a feature on the main page, so I searched the issues and found #109 and #237, so we both downloaded and installed gstreamer and restarted Nheko but it didn't do anything. Also, not sure if it's related, but neither of us could PM the other. We tried both by clicking each other's names and clicking the icon in that window and by clicking the plus icon and selecting "Start a direct chat" and entering each other's ID's and nothing happened.

### To Reproduce

No steps, just can't even find voice chat functionality. It appears to be non-existent. And can't change any of the related settings, either. Not sure if it matters, but I'm using the portable version and I think he was, too.

### Version

0.10.2-031a1295

### Operating system

Windows

### Installation method

Windows download

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment] 2023-01-18 05:48
Calls are currently not supported on Windows, see #641

**Comment by deepbluev7** [comment] 2023-01-18 05:49
Duplicate of #641

**Closed by deepbluev7** 2023-01-18 05:49 UTC
Labels: bug

**Comment by checkraisefold** [comment] 2023-11-14 03:49
Making progress on this issue, will make a fork soon hopefully if I can get the build fully working. I'll also revamp some of the Windows build instructions that are out of date in it.
Got gstreamer to fully link and mostly work using vcpkg with the vcpkg toolchain. However, gstreamer plugins aren't working for some reason; they're in the registry and I've confirmed that the Directsound plugin provides the audio/x-raw capability and Audio/Source class; however gst_device_monitor_start throws `No providers match the current filters`
