### ISSUE TITLE
font selector is unusable

### ISSUE THREAD

**Issue by mauke** [Nheko-Reborn/nheko#1261] opened 2023-01-04 14:17 UTC
### Describe the bug

The font selector in the preferences window is a simple dropdown menu of font names. Unfortunately, this dropdown is also quite narrow and only shows the first few characters of each font name, even on a wide screen. That makes it impossible to tell which font is actually being selected.

If you have a lot of fonts installed, you have to scroll for miles to find the one you're looking for because the dropdown just grows super tall.

### To Reproduce

1. Go to Settings / General
2. Click on the Font Family or Emoji Font Family dropdown
3. Scroll down for five miles
4. Get lost

### What happened?

A super tall and narrow dropdown appears where each visible entry is just "Noto Sans ...".

### Expected behavior

At minimum the full name of each font should be shown.

For a better user experience, a smarter font selector would be nice (including a font preview).

### Screenshots

![Screenshot from 2023-01-04 15-05-34](https://user-images.githubusercontent.com/278465/210573925-441ea0aa-4753-4e98-8627-018d57af1577.png)

### Version

0.10.2-3a6a9054

### Operating system

Linux

### Installation method

Flatpak nightly repo or download

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment] 2023-01-04 16:07
Duplicate of #1164

**Closed by deepbluev7** 2023-01-04 16:07 UTC
Labels: bug
