### ISSUE TITLE
Searching messages

### ISSUE THREAD

**Issue by vachan-maker** [Nheko-Reborn/nheko#703] opened 2021-08-30 02:28 UTC
### The Problem

- Searching is a feature that I miss in Nheko

### The Solution

Add a sear feature

### Alternatives

No alternatives yet.
I go to element for searching messages

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment] 2021-08-30 09:33
Duplicate of #8

**Closed by deepbluev7** 2021-08-30 09:33 UTC
Labels: enhancement
