### ISSUE TITLE
Notification of read messages blocked by Riot.IM

### ISSUE THREAD

**Issue by HeikoTietze** [Nheko-Reborn/nheko#120] opened 2020-02-17 14:41 UTC
I'm running Nheko on KDE/Arch Linux and am connected in parallel on Android via Riot. Messages show on the desktop nicely with a red indicator but are not reset until I read it on the mobile.

**Comment by deepbluev7** [comment] 2020-03-26 10:44
So, I tried reproducing it, but I really don't understand, what the issue is here:

Assuming I have unread notifications, so a red bubble in the notification tray from Nheko, in Nhekos room list, on Android and on my self hosted riot:

- When I read it on Riot Android, all the unread bubbles disappear
- Same when I read it in Riot Web
- When I read them in Nheko, they also disappear in the tray, in Riot Web and Riot Android

So I can't reproduce it. This may have been fixed in the development version or I just fail to understand the issue.

If you can still reproduce it, please describe the exact steps to do so. If you can provide screenshots or a short video, that would be even better, but please try to not send personal information. I'm going to close this for now, but if you can provide steps to reproduce it, I'll reopen it of course! It would be awesome, if you could try it with the latest master, but if that is too much effort, a reproduction with the latest stable (0.6.4 atm) would suffice. Thanks!

**Closed by deepbluev7** 2020-03-26 10:44 UTC

**Comment by HeikoTietze** [comment] 2020-03-26 11:07
Point is that the bubble does not disappear when I read the messages with Nheko. At least in my setup. Not a big deal if you cannot reproduce. Thanks for all your work.

**Comment by deepbluev7** [comment] 2020-03-26 11:19
That sounds more like a Riot bug though, since it works fine with everything else it seems? Have you tried reading the messages in other clients and see if Riot (Android?) updates?
