### ISSUE TITLE
Links in replies don't work

### ISSUE THREAD

**Issue by vachan-maker** [Nheko-Reborn/nheko#612] opened 2021-06-18 05:43 UTC
![2021-06-18 11_11_22-Window](https://user-images.githubusercontent.com/65799568/122512158-1388d000-d026-11eb-9a6a-27e53b1cbdea.png)
This link doesn't work upon clicking
I have to find the original message and then click on it.
![image](https://user-images.githubusercontent.com/65799568/122512449-7e3a0b80-d026-11eb-81f7-18802756c51d.png)

**Comment by deepbluev7** [comment] 2021-06-18 10:28
Duplicate of #529

**Closed by deepbluev7** 2021-06-18 10:28 UTC
Labels: bug
