### ISSUE TITLE
nheko starts over 5 minutes...

### ISSUE THREAD

**Issue by JeanPaulLucien** [Nheko-Reborn/nheko#1425] opened 2023-03-19 17:50 UTC
### Describe the bug

I wait too much time to see nheko.

### To Reproduce

1. Start nheko.

### What happened?

nheko starts very long time, several minutes.

### Version

0.11.3

### Operating system

Windows

### Installation method

Windows download

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment] 2023-03-19 18:02
You probably don't have your dbus set up correctly, so Nheko is blocked on accessing that.

**Comment by Lemntum** [comment] 2023-03-23 22:09
I've been experiencing this issue too since updating to the recent the Flatpak version.

The issue is caused by the process `gst-plugin-scanner -I /app/bin/io.github.NhekoReborn.Nheko` blocking the rest of startup. It takes several minutes to complete before letting the application launch, and eats up half the cpu in the meantime.

I see gstreamer was updated at the same time the issue started. https://github.com/flathub/io.github.NhekoReborn.Nheko/pull/12

If this is really a dbus issue, what is the expected configuration for dbus?

**Comment by deepbluev7** [comment] 2023-03-23 22:23
Hm, no, if you see gstreamer using most of the CPU, then that is probably the problem. However the original reporter adapted their report to say, they are on Windows, which isn't built with gstreamer support....

**Comment by deepbluev7** [comment] 2023-03-23 22:30
Can you run the flatpak with `GST_DEBUG=5` for debugging?

**Comment by Lemntum** [comment] 2023-03-23 22:56
Thanks for re-opening the issue.

Here's the output of `GST_DEBUG=5 /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=io.github.NhekoReborn.Nheko --file-forwarding io.github.NhekoReborn.Nheko @@u %u @@`.

[gst_log.txt](https://github.com/Nheko-Reborn/nheko/files/11056987/gst_log.txt)

**Comment by deepbluev7** [comment] 2023-03-23 23:02
That log says gstreamer took 5 seconds to scan all plugins, are you sure it takes 5 minutes?

**Comment by Lemntum** [comment] 2023-03-23 23:40
It has been starting faster since running it with the debug option enabled.

Previously I'd say it was taking closer to 3 minutes on my machine. (I did not time it exactly.) It also would happen only the first time launched after the system was started. Subsequent launches would be normal. This isn't happening now. Reinstalling seems to have made it start up even faster.

I'm not sure how to replicate it now, sorry.

**Comment by deepbluev7** [comment] 2023-03-24 00:22
I am assuming it was just some gstreamer cache file being outdated then and that that got updated now. Alternatively maybe there was a runtime bug that got fixed in between your reinstall. I'll close this until someone can repro and provide logs.

**Closed by deepbluev7** 2023-03-24 00:22 UTC
Labels: bug
