### ISSUE TITLE
scrolling room messages is choppy

### ISSUE THREAD

**Issue by iambumblehead** [Nheko-Reborn/nheko#860] opened 2021-12-28 17:48 UTC
### Describe the bug

scrolling room messages is "choppy" and otherwise difficult to describe. It feels like nheko tries to "snap" scroll position to messages as they go by. The snapping behaviour seems more dramatic when the messages being scrolled are longer --a paragraph or two and nested replies, but the behaviour is detectable in rooms with fewer messages as well.

Nheko is usable but messages can be difficult to read when sudden "snap" behaviour disorients things.

### To Reproduce

1. Open a room with messages (longer messages are probably "better" for reproducing)
2. Scroll up and down at various speeds
2. See that the scroll behaviour is not smooth but choppy

### Version

v0.9.1-37-g9eff123c | darwin

### Operating system

macOS

### Installation method

macOS DMG file

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment] 2021-12-30 06:15
Duplicate of #749

I did spend the last few days speeding up the rendering, which should make it a bit smoother, but the jumping issue will only be fixed with Qt6.

**Closed by deepbluev7** 2021-12-30 06:15 UTC
Labels: bug

**Comment by iambumblehead** [comment] 2021-12-30 06:28
@deepbluev7 I hope it also fixes this whitespace issue :) https://github.com/Nheko-Reborn/nheko/issues/633

**Comment by deepbluev7** [comment] 2021-12-30 06:30
That's part of https://bugreports.qt.io/browse/QTBUG-88495

**Comment by iambumblehead** [comment] 2021-12-30 18:24
@deepbluev7 I'm using the most recent nightly mac dmg. I do still see the issue, but I found something that may be useful.
 * _if the room is scrolled up and down while the mouse is over the **right-hand side** of the room,_ the experience is better.
 * _If the room is scrolled up and down while the mouse is over the **left-hand side** of the room,_ the experience is worse.

when the mouse is over the left-hand side while the room is scrolled with touchpad gesture, the scroll position can get "stuck" with the cursor ending up over the name bubble that pops out over a user's name and its not too hard to reproduce the "stuck" behaviour.  Maybe the popout bubbles degrade scroll performance and maybe they could be disabled when scroll is engaged.

**Comment by deepbluev7** [comment] 2021-12-30 23:49
@iambumblehead That particular issue should be fixed now. I had planned to do so for a while already, I just always forgot :D

**Comment by iambumblehead** [comment] 2021-12-31 01:11
awesome :) I'll look forward to trying out another of the nightly dmg in a few days
