### ISSUE TITLE
WebP image in chat crashes nheko

### ISSUE THREAD

**Issue by rakshazi** [Nheko-Reborn/nheko#451] opened 2021-02-04 11:56 UTC
### Describe the bug
Click on shared in chat WebP image crashes nheko

### To Reproduce
1. Start a chat or open existing chat
2. Send a webp image (not as file to download, but as image to preview)
3. Click on webp image to open view with image
4. Get nheko crash and `Aborted (core dumped)` message in console (even with `--debug` enabled no other messages)

### Expected behavior

Nheko shows image and does not crash

### Screenshots
Nope

### System:

- Nheko version: nheko 0.8.1-82de349
- Profile used: default
- Installation method: AUR
- Operating System: Manjaro Linux 20.2.1
- Qt version: 
- C++ compiler: 
- Desktop Environment: XFCE

### Logs
`Aborted (core dumped)`, nothing more

**Comment by deepbluev7** [comment] 2021-02-25 13:31
I can't reproduce this, can you create a backtrace?

**Comment by deepbluev7** [comment] 2021-04-28 18:07
Closing, because none can reproduce this.

**Closed by deepbluev7** 2021-04-28 18:07 UTC
Labels: bug
