### ISSUE TITLE
typing interrupted / frozen mid-message sometimes

### ISSUE THREAD

**Issue by Soundtoxin** [Nheko-Reborn/nheko#260] opened 2020-08-18 16:26 UTC
### Describe the bug
A few times now I'll go to start typing a message and suddenly no more letters are appearing. It may or may not have to do with my letters hitting the edge of the text box. Could be coincidence. This is annoying because I can't finish getting the thought typed out. Maybe it's because the server has just gone offline or something, but I don't think this should interrupt my typing anyway.

### To Reproduce
1. change to a new chat with C-k
2. start rapidly typing your message to your friends
3. it may be interrupted partway through

### Expected behavior
Let me finish typing, no matter what. Optionally inform me if the server has gone down with some symbol somewhere, but don't interrupt what I'm doing.

### System:

- Nheko version: 0.7.2
- Installation method: guix repository
- Operating System: Guix System
- Qt version: 5.14.2
- C++ compiler: gcc 7.5.0
- Desktop Environment: Sway
(I didn't build it myself, just checked what versions of stuff guix built it with)

### Logs
I believe the incident this time was at 11:05 or so, so here are some lines surrounding that time
```
[2020-08-18 11:02:30.528] [net] [info] trying to re-connect
[2020-08-18 11:05:59.965] [ui] [warning] Read index out of range
[2020-08-18 11:06:15.403] [net] [info] connectivity lost
[2020-08-18 11:06:37.395] [net] [info] trying to re-connect
[2020-08-18 11:07:07.523] [ui] [info] Trying to activate room !WhJNfooTCtjnYtVsPX:chat.weho.st
[2020-08-18 11:07:07.525] [ui] [info] Activated room !WhJNfooTCtjnYtVsPX:chat.weho.st
[2020-08-18 11:07:21.551] [net] [warning] failed to read_event (!WhJNfooTCtjnYtVsPX:chat.weho.st, )
[2020-08-18 11:07:21.632] [net] [info] connectivity lost
[2020-08-18 11:07:38.267] [qml] [warning] QVariant::save: unable to save type 'UserSettings::Presence' (type id: 1093).
 (:0, )
[2020-08-18 11:07:38.278] [qml] [warning] QVariant::save: unable to save type 'UserSettings::Presence' (type id: 1093).
 (:0, )
```

**Comment by deepbluev7** [comment] 2020-08-31 16:45
Duplicate of #258 imo

**Closed by deepbluev7** 2020-08-31 16:45 UTC
Labels: bug, duplicate

**Comment by Soundtoxin** [comment] 2020-08-31 19:45
Maybe, maybe not. I'm not sure if it's just due to server disconnection or not, since the only thing that tells me if I'm disconnected is displayed in the text box, so I'm guessing it can't show me if I was typing stuff.

**Comment by deepbluev7** [comment] 2020-08-31 20:06
In my experience it only happens, when you lose network connectivity. It may be related to the reconnection logic, but I have not yet seen this behaviour, when there were no reconnects. I guess we can revisit this, once #258 is fixed, but I'm fairly certain it has the same cause.

**Comment by Soundtoxin** [comment] 2020-08-31 20:50
Okay, sounds good to me.
