### ISSUE TITLE
Client runniing, but totally inactive (NomadBSD / FreeBSD)

### ISSUE THREAD

**Issue by AndrewMcSwain** [Nheko-Reborn/nheko#225] opened 2020-06-15 21:45 UTC
on system nomadBSD, which is a fork of freeBSDfor running the OS live on a USB with persistence. nheko acquired and installed as pre-built binary through `pkg install`

run `nheko` from command line
output is `ld-elf.so.1: /usr/local/lib/qt5/libQt5Svg.so.5: Undefined symbol "_ZTI14QObjectPrivate@Qt_5"`
wait 5 minutes
no response in ui or bash
`ps aux | grep nheko` only  shows grep process
output: nomad      5254   0.0  0.0    480    196  2  R+   18:26     0:00.00 grep nheko
i guess it isn't initializing

log file not found in location
`find / \-name "nheko" -print` reveals only binary locations
/usr/local/bin/nheko
/private/home/pkgs/bin/nheko

**Comment by deepbluev7** [comment] 2020-06-15 22:15
I had those issues a few times as well when developing. It usually meant, that nheko needed to be recompiled, because Qt or boost changed, so this may be a packaging issue. I'm not familiar with FreeBSD though and how their packaging works. I'm guessing compiling it yourself is a lot of effort?

**Comment by Mte90** [comment] 2020-06-30 11:01
I can confirm that recompiling on debian sid fixed. They moved to a new qt version.

**Comment by deepbluev7** [comment] 2021-03-21 18:23
Since this does not seem to be reproduceable, I will close it for now, unless someone can still reproduce this with the current master.

**Closed by deepbluev7** 2021-03-21 18:23 UTC
Labels: bug
