### ISSUE TITLE
nheko formats wrong a forwarded messages inside Telegram.

### ISSUE THREAD

**Issue by JeanPaulLucien** [Nheko-Reborn/nheko#1307] opened 2023-01-21 07:56 UTC
### Describe the bug

nheko formats wrong a forwarded messages inside Telegram.

### To Reproduce

You may using Telegram bridge forward message to your group in Telegram.
or
Using Nheko find a room with Telegram bridge, you should see forwared message.

### Version

0.10.2

### Operating system

Windows

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment] 2023-01-21 18:50
Duplicate of #1167

**Closed by deepbluev7** 2023-01-21 18:50 UTC
Labels: bug
