### ISSUE TITLE
switching to room on top of the list takes a double click

### ISSUE THREAD

**Issue by HarHarLinks** [Nheko-Reborn/nheko#464] opened 2021-02-06 13:12 UTC
### Describe the bug
I can switch to any room using a single click, except the room on top of the list.

### Expected behavior
Single click should obviously suffice

### System:

- Nheko version: aur/nheko 0.8.1-1
- Profile used: don't even know what this means
- Installation method: AUR
- Operating System: arch
- Qt version: compilation handled by aur pkgbuild (i guess 5.15.2-3)
- C++ compiler: compilation handled by aur pkgbuild (i have gcc 10.2.0-4 and clang 11.0.1-1 installed)
- Desktop Environment: sway/none/but i have gnome installed somewhere

**Comment by Jedi18** [comment] 2021-02-14 07:39
I can't reproduce this bug on windows.

**Comment by deepbluev7** [comment] 2021-06-16 21:40
Should be fixed or at least, I rewrote everything

**Closed by deepbluev7** 2021-06-16 21:40 UTC
Labels: bug
