### ISSUE TITLE
At registration screen, reCAPTCHA is always tried even if not in registration flows

### ISSUE THREAD

**Issue by maxidorius** [Nheko-Reborn/nheko#51] opened 2019-03-26 21:15 UTC
If the Homeserver returns a 401 with the following body for ` POST /_matrix/client/r0/register`:
```
{
  "session": "704e6a8b-d10a-4b64-92a3-d2b76e5005c1",
  "flows": [
    {
      "stages": [
        "m.login.password"
      ]
    }
  ]
}
```
then the client will prompt for reCAPTCHA, even tho it's not provided by the Homeserver.

Following discussing in the Matrix room, it seems like `m.login/password` is simply not supported. Context is [here](https://matrix.to/#/!evAqkPHZuPHIGeenhi:ocean.joedonofry.com/$1553634336882QbZSj:feneas.org?via=ocean.joedonofry.com&via=matrix.org&via=ru-matrix.org).

**Comment by deepbluev7** [comment] 2020-02-02 18:07
I'm guessing this can only be reproduced with other homeserver implementations than synapse, since synapse doesn't return the password flow on registration, when you already provided a password at the registration call. I'll add support for that anyway, when I'm fixing the auth/registration flows, but if there is a server I could test this one, I would be glad for that info!

**Comment by deepbluev7** [comment] 2020-02-23 11:02
So, this should be fixed. I didn't implement any cool widgets for the different flows and nheko mostly relies on the server fallback, but it shouldn't just assume recaptcha anymore.

**Closed by deepbluev7** 2020-02-23 11:02 UTC
