### ISSUE TITLE
Accepting Matrix Invites Crashes the Client

### ISSUE THREAD

**Issue by ThisNekoGuy** [Nheko-Reborn/nheko#871] opened 2022-01-03 02:10 UTC
### Describe the bug

**Disclaimer:**
The `gdb` debug log logs joining a less than appropriate server; I do not condone the contents of that server, I only used it as an example for processing this bug report since it was the only relevant example left to work from at the time.

------

A crash occurs when attempting to accept any matrix invite.
I tried to accept a chat invite, but I didn't have a debug build at the time and wasn't running it in a terminal so I didn't capture any information.

I had two more invites (of unknown origin) to chatrooms, so I used that for subsequent testing; not that the initial log report below was also before I had a debug build, so built a debug version and then (attempted) to use `gdb` (I've never used it before) with Nheko before testing with the final invite accessible to me.

### To Reproduce

1. Open Nheko
2. Receive an invite (optionally before opening Nheko)
3. Click the invite "chat" tab
4. Click accept
5. Nheko temporarily locks up
6. Nheko crashes

### What happened?

- Accepting Matrix invites crashes the client application with a "SIGABORT" response

### Expected behavior

- Accepting Matrix invites should not crash the client

### Version

0.9.1

### Operating system

Linux

### Installation method

Some repository (AUR)

### Qt version

5.15.2

### C++ compiler

  Clang 13.0.0

### Desktop Environment

KDE Plasma with Kwin Window Manager

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
neko-san@ARCH ~> nheko
Icon theme "gnome" not found.
Icon theme "ubuntu-mono-dark" not found.
Icon theme "Mint-X" not found.
Icon theme "elementary" not found.
Icon theme "gnome" not found.
[2022-01-02 19:29:50.683] [ui] [info] Restoring window size 1920x1013
[2022-01-02 19:29:50.717] [ui] [info] WebRTC: initialised GStreamer 1.18.5
[2022-01-02 19:29:50.983] [ui] [info] jdenticon plugin not found.
[2022-01-02 19:29:51.230] [ui] [debug] Profile requested
[2022-01-02 19:29:51.274] [ui] [debug] Status changed to 1
[2022-01-02 19:29:51.277] [ui] [debug] WebRTC: audio device added: Monitor of TU102 High Definition Audio Controller Digital Stereo (HDMI 2)
[2022-01-02 19:29:51.278] [ui] [debug] WebRTC: audio device added: HD-Audio Generic at 0xfca00000 irq 103
[2022-01-02 19:29:51.278] [ui] [debug] WebRTC: audio device added: HD-Audio Generic at 0xfca00000 irq 103
[2022-01-02 19:29:51.329] [ui] [info] starting nheko 0.9.1
[2022-01-02 19:29:51.333] [db] [debug] setting up cache
[2022-01-02 19:29:51.337] [db] [info] database ready
[2022-01-02 19:29:51.337] [db] [info] restoring state from cache
[2022-01-02 19:29:51.337] [db] [info] Invalidating self verification status
[2022-01-02 19:29:51.347] [db] [info] Restored 56 rooms from cache
[2022-01-02 19:29:51.358] [crypto] [info] ed25519   : OThU8cFz+9l6QudcSL38hlMxeoEj32CdLzWmwX/JreI
[2022-01-02 19:29:51.358] [crypto] [info] curve25519: nwcXuepFG+js0wfOi6eNbEmkXdv1cqwJsdvx6Dye1GE
[2022-01-02 19:29:51.358] [crypto] [info] Online key backup disabled.
[2022-01-02 19:29:51.358] [ui] [debug] Profile requested
[2022-01-02 19:29:51.358] [db] [debug] Marking user keys out of date: @neko-san:matrix.fedibird.com
[2022-01-02 19:29:52.096] [db] [debug] Updated user keys: @neko-san:matrix.fedibird.com
[2022-01-02 19:29:52.097] [db] [info] Invalidating self verification status
[2022-01-02 19:29:52.178] [net] [debug] sync completed: s4571222_15993537_111573_1091646_449468_393_46130_709849_8
[2022-01-02 19:29:52.178] [crypto] [debug] Updated server key count 50 signed_curve25519
[2022-01-02 19:29:52.178] [db] [debug] saving '{"event_id":"$raXm-jIDgdHt0qEIEPDiOS1slIsqK1p-W4jBqEwwogg","prev_batch":"s4571221_15993537_111573_1091646_449468_393_46130_709849_8"}'
[2022-01-02 19:29:52.178] [db] [info] mark room !fcaMJQswAXolRcxOfy:nibbana.jp as encrypted
[2022-01-02 19:29:52.178] [db] [debug] saving '{"event_id":"$UY8UpY4BDTSGNkQjGI0uVlFHI6S5kGep61lxJ7bnmUE","prev_batch":"s4571221_15993537_111573_1091646_449468_393_46130_709849_8"}'
[2022-01-02 19:29:52.178] [db] [warning] duplicate event '{"event_id":"$UY8UpY4BDTSGNkQjGI0uVlFHI6S5kGep61lxJ7bnmUE"}'
[2022-01-02 19:29:52.179] [db] [debug] Marking user keys out of date: @neko-san:matrix.fedibird.com
[2022-01-02 19:29:52.179] [db] [debug] Marking user keys out of date: @toneji:nibbana.jp
[2022-01-02 19:29:52.180] [ui] [debug] begin insert from 0 to 0
[2022-01-02 19:29:52.624] [db] [debug] Updated user keys: @neko-san:matrix.fedibird.com
[2022-01-02 19:29:52.624] [db] [debug] Updated user keys: @toneji:nibbana.jp
[2022-01-02 19:29:52.625] [db] [info] Invalidating self verification status
[2022-01-02 19:29:52.983] [crypto] [info] Fetched server key count 50 signed_curve25519
[2022-01-02 19:29:52.983] [crypto] [debug] Updated server key count 50 signed_curve25519
[2022-01-02 19:29:53.480] [net] [debug] sync completed: s4571222_15993539_111573_1091646_449468_393_46130_709849_8
[2022-01-02 19:29:53.480] [crypto] [debug] Updated server key count 50 signed_curve25519
[2022-01-02 19:29:53.636] [net] [info] TURN server(s) retrieved from homeserver:
[2022-01-02 19:29:53.636] [net] [info] username: 1641176993:@neko-san:matrix.fedibird.com
[2022-01-02 19:29:53.636] [net] [info] ttl: 3600 seconds
[2022-01-02 19:29:53.636] [net] [info] uri: turns:turn.fedibird.com?transport=udp
[2022-01-02 19:29:53.636] [net] [info] uri: turns:turn.fedibird.com?transport=tcp
[2022-01-02 19:29:53.636] [net] [info] uri: turn:turn.fedibird.com?transport=udp
[2022-01-02 19:29:53.636] [net] [info] uri: turn:turn.fedibird.com?transport=tcp
[2022-01-02 19:29:55.362] [net] [debug] sync completed: s4571222_15993540_111573_1091646_449468_393_46130_709849_8
[2022-01-02 19:29:55.362] [crypto] [debug] Updated server key count 50 signed_curve25519
[2022-01-02 19:29:58.234] [net] [debug] sync completed: s4571222_15993564_111573_1091646_449468_393_46130_709849_8
[2022-01-02 19:29:58.234] [crypto] [debug] Updated server key count 50 signed_curve25519
[2022-01-02 19:30:00.175] [net] [debug] sync completed: s4571222_15993565_111573_1091646_449468_393_46130_709849_8
[2022-01-02 19:30:00.175] [crypto] [debug] Updated server key count 50 signed_curve25519
[2022-01-02 19:30:02.398] [net] [debug] sync completed: s4571222_15993566_111573_1091646_449468_393_46130_709849_8
[2022-01-02 19:30:02.398] [crypto] [debug] Updated server key count 50 signed_curve25519
[2022-01-02 19:30:03.459] [net] [debug] sync completed: s4571222_15993567_111573_1091646_449468_393_46130_709849_8
[2022-01-02 19:30:03.459] [crypto] [debug] Updated server key count 50 signed_curve25519
[2022-01-02 19:30:04.885] [net] [debug] sync completed: s4571222_15993568_111573_1091646_449468_393_46130_709849_8
[2022-01-02 19:30:04.885] [crypto] [debug] Updated server key count 50 signed_curve25519
[2022-01-02 19:30:05.547] [qml] [debug] tapped !fcaMJQswAXolRcxOfy:nibbana.jp (qrc:/qml/RoomList.qml:145, onClicked)
[2022-01-02 19:30:05.547] [ui] [debug] Trying to switch to: !fcaMJQswAXolRcxOfy:nibbana.jp
[2022-01-02 19:30:05.548] [ui] [debug] Paginating room !fcaMJQswAXolRcxOfy:nibbana.jp, token s4571221_15993537_111573_1091646_449468_393_46130_709849_8
[2022-01-02 19:30:05.563] [ui] [debug] Switched to: !fcaMJQswAXolRcxOfy:nibbana.jp
[2022-01-02 19:30:05.563] [ui] [warning] Already loading older messages
[2022-01-02 19:30:05.816] [ui] [debug] data changed 0 to 0
[2022-01-02 19:30:05.816] [ui] [debug] data changed 0 to 0
[2022-01-02 19:30:05.816] [net] [debug] sync completed: s4571222_15993568_111573_1091647_449468_393_46130_709849_8
[2022-01-02 19:30:05.816] [crypto] [debug] Updated server key count 50 signed_curve25519
[2022-01-02 19:30:06.033] [net] [debug] sync completed: s4571222_15993568_111573_1091647_449469_393_46130_709849_8
[2022-01-02 19:30:06.033] [crypto] [debug] Updated server key count 50 signed_curve25519
[2022-01-02 19:30:06.033] [db] [debug] Fully read: $UY8UpY4BDTSGNkQjGI0uVlFHI6S5kGep61lxJ7bnmUE
[2022-01-02 19:30:06.334] [ui] [debug] begin insert from 1 to 9
[2022-01-02 19:30:06.334] [ui] [debug] data changed 0 to 0
[2022-01-02 19:30:06.354] [ui] [debug] Paginating room !fcaMJQswAXolRcxOfy:nibbana.jp, token t1-4571213_15993537_111573_1091646_449468_393_46130_709849_8
[2022-01-02 19:30:06.361] [net] [debug] sync completed: s4571222_15993568_111573_1091647_449469_393_46130_709850_8
[2022-01-02 19:30:06.361] [crypto] [debug] Updated server key count 50 signed_curve25519
[2022-01-02 19:30:06.361] [db] [debug] Marking user keys out of date: @lenzj:matrix.org
[2022-01-02 19:30:06.580] [db] [debug] Updated user keys: @lenzj:matrix.org
[2022-01-02 19:30:06.580] [db] [debug] Master key of @lenzj:matrix.org changed:
old: 1
new: 1
[2022-01-02 19:30:06.901] [net] [debug] sync completed: s4571222_15993568_111573_1091648_449469_393_46130_709851_8
[2022-01-02 19:30:06.901] [crypto] [debug] Updated server key count 50 signed_curve25519
[2022-01-02 19:30:06.901] [db] [debug] Marking user keys out of date: @lenzj:matrix.org
[2022-01-02 19:30:07.138] [net] [debug] sync completed: s4571223_15993568_111573_1091648_449469_393_46130_709851_8
[2022-01-02 19:30:07.138] [crypto] [debug] Updated server key count 50 signed_curve25519
[2022-01-02 19:30:07.138] [db] [debug] saving '{"event_id":"$XA8ZNMxC9nGKz7eSGh4lyUxk2TF_3GrtZNyMzGksDFQ","prev_batch":"s4571222_15993568_111573_1091648_449469_393_46130_709851_8"}'
[2022-01-02 19:30:07.138] [ui] [debug] begin insert from 0 to 0
[2022-01-02 19:30:07.139] [db] [debug] Updated user keys: @lenzj:matrix.org
[2022-01-02 19:30:11.134] [qml] [debug] tapped !fzfHhoTplYBEXfWOaI:matrix.org (qrc:/qml/RoomList.qml:145, onClicked)
[2022-01-02 19:30:11.134] [ui] [debug] Trying to switch to: !fzfHhoTplYBEXfWOaI:matrix.org
[2022-01-02 19:30:11.134] [ui] [debug] Switched to (preview): !fzfHhoTplYBEXfWOaI:matrix.org
[2022-01-02 19:30:11.433] [ui] [debug] Wrote: /home/neko-san/.cache/nheko/nheko/media_cache/MzAwMC5jaGF0L3JhR3FRU0xETVBScE12SHFtcFRoQ3dwSA_520x520_crop_radius100
terminate called after throwing an instance of 'lmdb::runtime_error'
  what():  mdb_dbi_open: Permission denied
Error: signal 6:
nheko(_Z17stacktraceHandleri+0x3d)[0x562225bd199d]
/usr/lib/libc.so.6(+0x3cda0)[0x7f4845929da0]
/usr/lib/libc.so.6(gsignal+0x142)[0x7f4845929d22]
/usr/lib/libc.so.6(abort+0x116)[0x7f4845913862]
/usr/lib/libstdc++.so.6(+0x99802)[0x7f4845cd2802]
/usr/lib/libstdc++.so.6(+0xa5c8a)[0x7f4845cdec8a]
/usr/lib/libstdc++.so.6(+0xa5cf7)[0x7f4845cdecf7]
/usr/lib/libstdc++.so.6(+0xa5f8e)[0x7f4845cdef8e]
nheko(+0x305802)[0x5622258e2802]
nheko(+0x4a3773)[0x562225a80773]
nheko(_ZN5Cache20getMembersFromInviteERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEmm+0x61)[0x562225ad0451]
nheko(_ZN13RoomlistModel12acceptInviteE7QString+0xe7)[0x562225940ca7]
nheko(+0x60a816)[0x562225be7816]
nheko(+0x60a52f)[0x562225be752f]
nheko(_ZN21FilteredRoomlistModel11qt_metacallEN11QMetaObject4CallEiPPv+0x7d)[0x562225be7e1d]
/usr/lib/libQt5Qml.so.5(+0x29171a)[0x7f48478b571a]
/usr/lib/libQt5Qml.so.5(+0x17d290)[0x7f48477a1290]
/usr/lib/libQt5Qml.so.5(_ZNK3QV413QObjectMethod12callInternalEPKNS_5ValueES3_i+0x43a)[0x7f48477a1a3a]
/usr/lib/libQt5Qml.so.5(+0x191a08)[0x7f48477b5a08]
/usr/lib/libQt5Qml.so.5(+0x198f46)[0x7f48477bcf46]
/usr/lib/libQt5Qml.so.5(_ZN3QV48Function4callEPKNS_5ValueES3_iPKNS_16ExecutionContextE+0x201)[0x7f4847761d81]
/usr/lib/libQt5Qml.so.5(_ZN24QQmlJavaScriptExpression8evaluateEPN3QV48CallDataEPb+0x198)[0x7f48478d8c38]
/usr/lib/libQt5Qml.so.5(_ZN25QQmlBoundSignalExpression8evaluateEPPv+0x36c)[0x7f4847884b2c]
/usr/lib/libQt5Qml.so.5(+0x261a3c)[0x7f4847885a3c]
/usr/lib/libQt5Qml.so.5(_ZN12QQmlNotifier10emitNotifyEP20QQmlNotifierEndpointPPv+0x215)[0x7f48478b5615]
/usr/lib/libQt5Core.so.5(+0x2b47ce)[0x7f484644e7ce]
/usr/lib/libQt5QuickTemplates2.so.5(_ZN27QQuickAbstractButtonPrivate13handleReleaseERK7QPointF+0x12a)[0x7f483bcceb2a]
/usr/lib/libQt5QuickTemplates2.so.5(_ZN13QQuickControl17mouseReleaseEventEP11QMouseEvent+0x81)[0x7f483bcf2ea1]
/usr/lib/libQt5Quick.so.5(_ZN10QQuickItem5eventEP6QEvent+0x1fb)[0x7f4847c9fe1b]
/usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x86)[0x7f48470014a6]
/usr/lib/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x138)[0x7f484641d4b8]
/usr/lib/libQt5Quick.so.5(_ZN19QQuickWindowPrivate17deliverMouseEventEP23QQuickPointerMouseEvent+0x1c3)[0x7f4847cbaca3]
/usr/lib/libQt5Quick.so.5(_ZN19QQuickWindowPrivate19deliverPointerEventEP18QQuickPointerEvent+0x70)[0x7f4847cbbe50]
/usr/lib/libQt5Gui.so.5(_ZN7QWindow5eventEP6QEvent+0x15d)[0x7f484696225d]
/usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x86)[0x7f48470014a6]
/usr/lib/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x138)[0x7f484641d4b8]
/usr/lib/libQt5QuickWidgets.so.5(_ZN12QQuickWidget17mouseReleaseEventEP11QMouseEvent+0x97)[0x7f4848040e57]
/usr/lib/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0x7b6)[0x7f484703eb36]
/usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x86)[0x7f48470014a6]
/usr/lib/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0xbea)[0x7f48470060ba]
/usr/lib/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x138)[0x7f484641d4b8]
/usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Ebb+0x1ab)[0x7f4847004c8b]
/usr/lib/libQt5Widgets.so.5(+0x1b9fb9)[0x7f484705afb9]
/usr/lib/libQt5Widgets.so.5(+0x1bb629)[0x7f484705c629]
/usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x86)[0x7f48470014a6]
/usr/lib/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x138)[0x7f484641d4b8]
/usr/lib/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE+0x5df)[0x7f4846952fbf]
/usr/lib/libQt5Gui.so.5(_ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0xb5)[0x7f484693eb25]
/usr/lib/libQt5XcbQpa.so.5(+0x668c0)[0x7f48416088c0]
/usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x26c)[0x7f4845edf52c]
fish: Job 1, 'nheko' terminated by signal SIGABRT (Abort)
neko-san@ARCH ~ [SIGABRT]>
```

### Backtrace

```shell
neko-san@ARCH ~> gdb /usr/bin/nheko
GNU gdb (GDB) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
  File "<string>", line 1
    import sys
IndentationError: unexpected indent
/home/neko-san/.gdbinit:7: Error in sourced command file:
Error while executing Python code.
Reading symbols from /usr/bin/nheko...
(gdb) run
Starting program: /usr/bin/nheko 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff0c7c640 (LWP 53738)]
[New Thread 0x7fffeabe9640 (LWP 53739)]
[New Thread 0x7fffe9a72640 (LWP 53740)]
[New Thread 0x7fffe9271640 (LWP 53741)]
[New Thread 0x7fffe8a70640 (LWP 53742)]
[New Thread 0x7fffdbfff640 (LWP 53743)]
[New Thread 0x7fffdb7fe640 (LWP 53744)]
[New Thread 0x7fffdaffd640 (LWP 53745)]
[New Thread 0x7fffda7fc640 (LWP 53746)]
[New Thread 0x7fffd9ffb640 (LWP 53747)]
[New Thread 0x7fffd97fa640 (LWP 53748)]
[New Thread 0x7fffd8ff9640 (LWP 53749)]
[New Thread 0x7fffb3fff640 (LWP 53750)]
[New Thread 0x7fffbbfff640 (LWP 53751)]
[New Thread 0x7fffbb7fe640 (LWP 53752)]
[New Thread 0x7fffbaffd640 (LWP 53753)]
[New Thread 0x7fffba7fc640 (LWP 53754)]
[New Thread 0x7fffb9ffb640 (LWP 53755)]
Icon theme "gnome" not found.
Icon theme "ubuntu-mono-dark" not found.
Icon theme "Mint-X" not found.
Icon theme "elementary" not found.
Icon theme "gnome" not found.
[2022-01-02 19:56:20.627] [ui] [info] Restoring window size 1920x1013
[2022-01-02 19:56:20.663] [ui] [info] WebRTC: initialised GStreamer 1.18.5
[New Thread 0x7fffb8dea640 (LWP 53756)]
[New Thread 0x7fffb37fe640 (LWP 53757)]
[New Thread 0x7fffb2ffd640 (LWP 53758)]
[Thread 0x7fffb2ffd640 (LWP 53758) exited]
[New Thread 0x7fffb2ffd640 (LWP 53759)]
[Thread 0x7fffb2ffd640 (LWP 53759) exited]
[New Thread 0x7fffb2ffd640 (LWP 53760)]
[2022-01-02 19:56:20.947] [ui] [info] jdenticon plugin not found.
[2022-01-02 19:56:21.590] [ui] [debug] Profile requested
[New Thread 0x7fffb0dbf640 (LWP 53761)]
[2022-01-02 19:56:21.634] [ui] [debug] Status changed to 1
[2022-01-02 19:56:21.638] [ui] [debug] WebRTC: audio device added: Monitor of TU102 High Definition Audio Controller Digital Stereo (HDMI 2)
[2022-01-02 19:56:21.638] [ui] [debug] WebRTC: audio device added: HD-Audio Generic at 0xfca00000 irq 103
[2022-01-02 19:56:21.638] [ui] [debug] WebRTC: audio device added: HD-Audio Generic at 0xfca00000 irq 103
[2022-01-02 19:56:21.688] [ui] [info] starting nheko 0.9.1
[New Thread 0x7fff79f44640 (LWP 53762)]
[2022-01-02 19:56:21.692] [db] [debug] setting up cache
[2022-01-02 19:56:21.695] [db] [info] database ready
[2022-01-02 19:56:21.696] [db] [info] restoring state from cache
[2022-01-02 19:56:21.696] [db] [info] Invalidating self verification status
[New Thread 0x7fff79743640 (LWP 53763)]
[Thread 0x7fff79743640 (LWP 53763) exited]
[2022-01-02 19:56:21.706] [db] [info] Restored 57 rooms from cache
[2022-01-02 19:56:21.717] [crypto] [info] ed25519   : OThU8cFz+9l6QudcSL38hlMxeoEj32CdLzWmwX/JreI
[2022-01-02 19:56:21.717] [crypto] [info] curve25519: nwcXuepFG+js0wfOi6eNbEmkXdv1cqwJsdvx6Dye1GE
[2022-01-02 19:56:21.717] [crypto] [info] Online key backup disabled.
[2022-01-02 19:56:21.718] [ui] [debug] Profile requested
[2022-01-02 19:56:21.718] [db] [debug] Marking user keys out of date: @neko-san:matrix.fedibird.com
[2022-01-02 19:56:22.335] [db] [debug] Updated user keys: @neko-san:matrix.fedibird.com
[2022-01-02 19:56:22.336] [db] [info] Invalidating self verification status
[2022-01-02 19:56:22.508] [crypto] [info] Fetched server key count 50 signed_curve25519
[2022-01-02 19:56:22.508] [crypto] [debug] Updated server key count 50 signed_curve25519
[2022-01-02 19:56:23.030] [net] [debug] sync completed: s4571596_15994886_111735_1091821_449496_393_46131_710797_8
[2022-01-02 19:56:23.030] [crypto] [debug] Updated server key count 50 signed_curve25519
[2022-01-02 19:56:23.030] [db] [debug] saving '{"event_id":"$ziIi5ZQbm16CnVd-miBWo7sJMOIInZD4oqFuMwufkjs","prev_batch":"s4571543_15994886_111735_1091821_449496_393_46131_710797_8"}'
[2022-01-02 19:56:23.031] [db] [debug] saving '{"event_id":"$9Qs8Dv3A-FQsQCU5HE8OcOWOWwPnGGTzSj8_FHO8WX0","prev_batch":"s4571595_15994886_111735_1091821_449496_393_46131_710797_8"}'
[2022-01-02 19:56:23.031] [db] [debug] saving '{"event_id":"$Q95MAOrC1c4CQ72zRgjiJO_pgT0GYkWg7q4aQCRqGmo","prev_batch":"s4571581_15994886_111735_1091821_449496_393_46131_710797_8"}'
[2022-01-02 19:56:23.031] [db] [debug] saving '{"event_id":"$IUxHAEeExHNndEgGRa3B1tcEQ6Z_T-p2jkZYonJg3xg"}'
[2022-01-02 19:56:23.031] [db] [debug] saving '{"event_id":"$LVAdENkG1BjJBQliqV9GbgA9XhqMHHqvixf9JyntXUw"}'
[2022-01-02 19:56:23.031] [db] [debug] saving '{"event_id":"$Sr8sjj_uhETb75x_hRBSoCp2nYHdr8HP0K7mQ19Hr3Y","prev_batch":"s4571578_15994886_111735_1091821_449496_393_46131_710797_8"}'
[2022-01-02 19:56:23.031] [db] [debug] saving '{"event_id":"$U8GPqM-bjvsMyvW57LPMxwfucXNGGt06Da4ZQoHRWII"}'
[2022-01-02 19:56:23.031] [db] [debug] saving '{"event_id":"$Dh8B3KGAZxTkudIWL-9GKIK7Ph6yzx3P1FBS0PlQrag","prev_batch":"s4571570_15994886_111735_1091821_449496_393_46131_710797_8"}'
[2022-01-02 19:56:23.031] [db] [debug] saving '{"event_id":"$RpIGqJPJyKA53YU3FVtE9MaJK3d32LqF4MiGct2AYBw"}'
[2022-01-02 19:56:23.031] [db] [debug] saving '{"event_id":"$HlXJbRxum8FvXif7ZDgzx93iZAmTFm2E1H_4yP0eOJs"}'
[2022-01-02 19:56:23.032] [db] [debug] Marking user keys out of date: @kdeneon:matrix.org
[2022-01-02 19:56:23.032] [db] [debug] Marking user keys out of date: @psykadelik:3000.chat
[2022-01-02 19:56:23.032] [db] [debug] Marking user keys out of date: @rei:anontier.nl
[2022-01-02 19:56:23.032] [db] [debug] Marking user keys out of date: @federicodschonborn:matrix.org
[2022-01-02 19:56:23.032] [db] [debug] Marking user keys out of date: @xldrake:envs.net
[2022-01-02 19:56:23.032] [db] [debug] Marking user keys out of date: @solbun:anontier.nl
[2022-01-02 19:56:23.033] [ui] [debug] begin insert from 0 to 0
[2022-01-02 19:56:23.034] [ui] [debug] begin insert from 0 to 0
[2022-01-02 19:56:23.034] [ui] [debug] begin insert from 0 to 2
[2022-01-02 19:56:23.034] [ui] [debug] data changed 1 to 1
[2022-01-02 19:56:23.037] [ui] [debug] begin insert from 0 to 1
[2022-01-02 19:56:23.037] [ui] [debug] data changed 0 to 0
[2022-01-02 19:56:23.037] [ui] [debug] begin insert from 0 to 2
[2022-01-02 19:56:23.811] [net] [info] TURN server(s) retrieved from homeserver:
[2022-01-02 19:56:23.811] [net] [info] username: 1641178583:@neko-san:matrix.fedibird.com
[2022-01-02 19:56:23.811] [net] [info] ttl: 3600 seconds
[2022-01-02 19:56:23.811] [net] [info] uri: turns:turn.fedibird.com?transport=udp
[2022-01-02 19:56:23.811] [net] [info] uri: turns:turn.fedibird.com?transport=tcp
[2022-01-02 19:56:23.811] [net] [info] uri: turn:turn.fedibird.com?transport=udp
[2022-01-02 19:56:23.811] [net] [info] uri: turn:turn.fedibird.com?transport=tcp
[2022-01-02 19:56:24.140] [db] [debug] Updated user keys: @federicodschonborn:matrix.org
[2022-01-02 19:56:24.140] [db] [debug] Updated user keys: @kdeneon:matrix.org
[2022-01-02 19:56:24.140] [db] [debug] Updated user keys: @psykadelik:3000.chat
[2022-01-02 19:56:24.140] [db] [debug] Updated user keys: @rei:anontier.nl
[2022-01-02 19:56:24.140] [db] [debug] Updated user keys: @solbun:anontier.nl
[2022-01-02 19:56:24.140] [db] [debug] Updated user keys: @xldrake:envs.net
[2022-01-02 19:56:24.324] [net] [debug] sync completed: s4571596_15994886_111735_1091821_449496_393_46131_710800_8
[2022-01-02 19:56:24.324] [crypto] [debug] Updated server key count 50 signed_curve25519
[2022-01-02 19:56:24.324] [db] [debug] Marking user keys out of date: @psykadelik:3000.chat
[2022-01-02 19:56:24.528] [net] [debug] sync completed: s4571596_15994887_111735_1091821_449496_393_46131_710800_8
[2022-01-02 19:56:24.528] [crypto] [debug] Updated server key count 50 signed_curve25519
[2022-01-02 19:56:24.531] [db] [debug] Updated user keys: @psykadelik:3000.chat
[2022-01-02 19:56:28.626] [net] [debug] sync completed: s4571596_15994888_111736_1091822_449496_393_46131_710800_8
[2022-01-02 19:56:28.626] [crypto] [debug] Updated server key count 50 signed_curve25519
[2022-01-02 19:56:30.775] [net] [debug] sync completed: s4571596_15994889_111736_1091822_449496_393_46131_710800_8
[2022-01-02 19:56:30.775] [crypto] [debug] Updated server key count 50 signed_curve25519
[2022-01-02 19:56:32.823] [net] [debug] sync completed: s4571596_15994889_111736_1091822_449496_393_46131_710803_8
[2022-01-02 19:56:32.823] [crypto] [debug] Updated server key count 50 signed_curve25519
[2022-01-02 19:56:32.823] [db] [debug] Marking user keys out of date: @seirdy:seirdy.one
[2022-01-02 19:56:33.029] [db] [debug] Updated user keys: @seirdy:seirdy.one
[2022-01-02 19:56:34.981] [qml] [debug] tapped !UPsqJAKJwKaqqYkxNZ:cutefunny.art (qrc:/qml/RoomList.qml:145, onClicked)
[2022-01-02 19:56:34.981] [ui] [debug] Trying to switch to: !UPsqJAKJwKaqqYkxNZ:cutefunny.art
[2022-01-02 19:56:34.981] [ui] [debug] Switched to (preview): !UPsqJAKJwKaqqYkxNZ:cutefunny.art
[2022-01-02 19:56:35.248] [ui] [debug] Wrote: /home/neko-san/.cache/nheko/nheko/media_cache/Y3V0ZWZ1bm55LmFydC92bW5TaFVmWmxabEpieGRDeXBKdFZ1cHQ_520x520_crop_radius100
terminate called after throwing an instance of 'lmdb::runtime_error'
  what():  mdb_dbi_open: Permission denied

Thread 1 "nheko" received signal SIGABRT, Aborted.
0x00007ffff519ad22 in raise () from /usr/lib/libc.so.6
(gdb)
```

**Comment by deepbluev7** [comment] 2022-01-03 02:32
Duplicate of #857 

I'll see if I can fix that soon.

**Comment by deepbluev7** [comment] 2022-01-03 02:34
Duplicate of #857

**Closed by deepbluev7** 2022-01-03 02:34 UTC
Labels: bug
