### ISSUE TITLE
Support voice and video calls on Windows

### ISSUE THREAD

**Issue by deepbluev7** [Nheko-Reborn/nheko#641] opened 2021-07-15 21:47 UTC
Screen capture support should be possible using gdiscreencap: https://gstreamer.freedesktop.org/documentation/winscreencap/gdiscreencapsrc.html?gi-language=c

Only need to write some additional code to select a window and such.

**Comment by evren320** [comment] 2022-08-05 21:56
when this feature would be completed?

**Comment by vertigo220** [comment] 2023-01-18 05:56
Not sure why my issue was marked as a duplicate of this one and closed, since this is about video calls and mine was about voice calls, but the main page should specify that this feature doesn't work on Windows. My friend and I wasted a good bit of time on this specifically because it clearly states that VoIP is supported.

**Comment by deepbluev7** [comment] 2023-01-18 05:59
Well, in any case calls on windows need the gstreamer dependencies to be packaged, which is not the case yet. While screen sharing will need some extra work on Windows, this issue in general is about calls as a whole or at least that was the intention originally :3

**Comment by vertigo220** [comment] 2023-01-18 06:07
At least with the changed title it fits. Wasn't against the idea of merging, just didn't make sense to call it a "duplicate." As I said in the other issue, we installed gstreamer but it still didn't work, so I'm guessing there's more to it than that. Just that the other issues I linked there seemed to suggest that's what was needed.

I just hope you'll update the main page, because as much as I like the idea of Nheko, voice and, to a lesser extent, screen sharing are requirements, so Nheko won't work for me, and had I known that, I wouldn't have spent the time on it. I'll definitely be keeping an eye out for this functionality to be added, though, and I can help with testing if needed.

**Comment by deepbluev7** [comment] 2023-01-18 06:33
Just installing gstreamer won't fix it. It needs to be there during build time (and then installed together with Nheko, if it gets packaged). We did test that that works before and it worked okayish, it could however have regressed. But we have no Windows devs, so this issue isn't seeing very much action. But yeah, we should update the README.

**Comment by HybridEidolon** [comment] 2023-06-05 18:28
If this is just an issue of making sure gstreamer is available at build time, the minimum gstreamer features needed could be [provided via vcpkg](https://vcpkg.link/ports/gstreamer) instead of requiring developers and packagers to go through the trouble of building it separately for the target toolchain.

**Closed** 2024-05-10 19:22 UTC
Labels: enhancement, voip
