### ISSUE TITLE
While creating/joining a room, the popup doesn't minimize back.

### ISSUE THREAD

**Issue by dhogaivannan** [Nheko-Reborn/nheko#153] opened 2020-03-20 06:05 UTC
### Describe the bug
When I try to create/join room, the popup appears but it stays forever even while opening up other applications,whereas the background Nheko minimizes properly.

### Expected behavior
To add a minimize button to that mini pop-up or let that popup acts with the command whatever given to the Nheko app.

### Screenshots
![aaswq](https://user-images.githubusercontent.com/6285333/77140196-df2f0880-6a9e-11ea-8bc2-53cc34b81dbe.PNG)

**Comment by deepbluev7** [comment] 2021-04-28 18:17
Can't reproduce and no further info provided, so I am closing this.

**Closed by deepbluev7** 2021-04-28 18:17 UTC
Labels: bug, info needed
