### ISSUE TITLE
Mute messages from a particular user in a room

### ISSUE THREAD

**Issue by vachan-maker** [Nheko-Reborn/nheko#706] opened 2021-09-02 04:12 UTC
### The Problem

The problem
- some users who join a room instantly spam the room with useless junk. Sometimes, I don't want to see any messages from that user in the room
- some rooms have gitlab/github CI bots. Yes, they are useful but its not to everyone. So I would like to hide the messages sent by the bot as well.

### The Solution

An option in user's room profile page to mute the user. Right next to the kick, ban and start private chat option.
![2021-09-02 09_40_07-Window](https://user-images.githubusercontent.com/65799568/131780528-f2f35b28-2fdc-495c-b8db-9a70741a5320.png)

### Alternatives

No alternatives

### Additional context

Element has this feature.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment] 2021-09-02 13:41
Duplicate of #546 

(But you probably couldn't find that with your description :3)

**Closed by deepbluev7** 2021-09-02 13:41 UTC
Labels: enhancement

**Comment by vachan-maker** [comment] 2021-09-02 14:14
> 
> 
> Duplicate of #546
> 
> (But you probably couldn't find that with your description :3)

I am bad at finding opened issues😫

Thanks Nico
