### ISSUE TITLE
Event notification doesn't clear when rooms have invisible Events

### ISSUE THREAD

**Issue by redsky17** [Nheko-Reborn/nheko#65] opened 2019-05-12 17:20 UTC
The blue notification bar to the left of rooms doesn't clear when the room is read if the room contains events that nheko doesn't show in the timeline.

Demonstration:
![GIF Showing Bug](https://ocean.joedonofry.com/_matrix/media/v1/download/ocean.joedonofry.com/xugnnwkHfxfdywgKPRrQsvWY)

**Comment by deepbluev7** [comment] 2020-02-23 20:58
I fixed that for most cases. There are still some edge cases, where this can happen, i.e. when the full room consists of state events, but one ancient message, that can't be marked as read, but it mostly happens in abandoned or otherwise stale rooms, So I don't consider it an issue.

**Comment by deepbluev7** [comment] 2020-02-23 21:03
Oops, seems like I celebrated too fast!

**Comment by deepbluev7** [comment] 2020-02-23 21:48
So, I think, I figured out the read events bug:

- We only store messages in the db, not all events
- If you are in a room, where the last even is a state event, that isn't stored in the db
- If the state event gets marked as read, you can't mark the message before it as read anymore
- If we now look up, if the room is fully read, we notice, that the message before the state event isn't read -> we mark the room as unread

Should we just store all events in the db? In that case, should I rename the db from messages to events or timeline? Currently the messages db is also limited to the 30 most recent messages, so a huge state event count could break our display of the last message text. Alternatively we could add a separate db, where we store all messages. That way one could theoretically use nheko offline and we could populate the qml timeline from that, until we run out of cache and need to load more from the network. Anyway, properly fixing this is hard!

**Comment by deepbluev7** [comment] 2020-02-24 00:11
I think I fixed it now. If anyone can still reproduce it with messages received after updating to the newest version with this date, please reopen. It won't be fixed for old messages received before this fix, since I can't easily obtain their event id and I don't want to force everyone to urge their cache just for this.

**Closed by deepbluev7** 2020-02-24 00:11 UTC
Labels: bug
