### ISSUE TITLE
HTML entities not always rendered

### ISSUE THREAD

**Issue by geekosaur** [Nheko-Reborn/nheko#1763] opened 2024-06-26 00:32 UTC
### Describe the bug

I sent the following sequence (we're fixing a problem with a software release):
```
`for v in 3.12.1.0 latest; do curl -X PURGE "http://downloads.haskell.org/~cabal/cabal-install-$v"; for f in '' *; do curl -X PURGE "http://downloads.haskell.org/~cabal/cabal-install-$v/$f"; done; done`
```
It rendered as:
```
for v in 3.12.1.0 latest; do curl -X PURGE "http://downloads.haskell.org/~cabal/cabal-install-$v&quot;; for f in '' *; do curl -X PURGE "http://downloads.haskell.org/~cabal/cabal-install-$v/$f&quot;; done; done
```
Note the `&quot;`s.

I'm not sure if this is caused by the immediately following semicolons or something else.

### To Reproduce

As above.

### What happened?

As above, it was displayed with `&quot;`s instead of `"`s.

### Expected behavior

It should have rendered the `&quot;` entities.

### Screenshots

![Screenshot_2024-06-25_20-31-28](https://github.com/Nheko-Reborn/nheko/assets/2036384/51b8aa53-6bcc-44ad-a483-4acac35eb727)

### Version

0.11.3-80ab0394

### Operating system

Linux

### Installation method

Flatpak nightly repo or download

### Desktop Environment

MATE with xmonad as window manager

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment] 2024-07-27 14:21
Duplicate of https://github.com/Nheko-Reborn/nheko/issues/1482

This is a problem of our linkifier.

**Closed by deepbluev7** 2024-07-27 14:21 UTC
Labels: bug
