### ISSUE TITLE
Inline preview for image and video links

### ISSUE THREAD

**Issue by lboklin** [Nheko-Reborn/nheko#930] opened 2022-02-11 07:43 UTC
### The Problem

It's common that links to images and videos are posted and you have to have to click on them to see what they are.

### The Solution

Display the linked media directly inline similar to if they had been sent as files.

### Alternatives

1. Show a smaller preview/thumbnail you can click on and it shows it in a bigger size
2. Feature a generic link inline preview of the linked website, with thumbnail and a text snippet, similar to Element

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment] 2022-02-11 18:17
Duplicate of #561

**Closed by deepbluev7** 2022-02-11 18:17 UTC
Labels: enhancement
