### ISSUE TITLE
Long prefomatted message missing scroll bars in replys

### ISSUE THREAD

**Issue by Artiom-M** [Nheko-Reborn/nheko#467] opened 2021-02-09 10:25 UTC
This is how it looks like when a big preformatted block is cited in the reply.
![image](https://user-images.githubusercontent.com/4058815/107349921-e7f85500-6b1c-11eb-9aa6-3f16f96aedf2.png)
The same message in elements is fully visible with scollbar

**Comment by deepbluev7** [comment] 2021-02-09 16:58
Preformatted messages in general have no scrollbars in Nheko. That may be worth fixing. On the other hand, replies have intentionally a limited height, since otherwise replying t a long message wastes a lot of space. Instead the idea is to be able to navigate to the original message, by clicking on the reply, but that is currently a bit broken for various reasons.

**Comment by deepbluev7** [comment] 2021-02-21 02:42
Closing this now, as this is mostly working as intended to limit the height of the reply. It could look nicer though. You should be able to click on the reply to scroll up to it in the current development version to see the full message.

**Closed by deepbluev7** 2021-02-21 02:42 UTC
Labels: bug
