### ISSUE TITLE
AppImage give out version `Qt_5.15' not found on startup

### ISSUE THREAD

**Issue by tusooa** [Nheko-Reborn/nheko#781] opened 2021-11-02 21:41 UTC
### Describe the bug

Using nheko-master-8beeba8e-x86_64.AppImage

It gives the error message as follows.

### To Reproduce

Run appimage

### What happened?

```
] ~/Downloads/nheko-master-8beeba8e-x86_64.AppImage
/tmp/.mount_nheko-xs2cei//usr/bin/nheko: /tmp/.mount_nheko-xs2cei//usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /tmp/.mount_nheko-xs2cei//usr/bin/nheko)
/tmp/.mount_nheko-xs2cei//usr/bin/nheko: /tmp/.mount_nheko-xs2cei//usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /usr/lib64/libQt5Svg.so.5)
/tmp/.mount_nheko-xs2cei//usr/bin/nheko: /tmp/.mount_nheko-xs2cei//usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /usr/lib64/libQt5Multimedia.so.5)
/tmp/.mount_nheko-xs2cei//usr/bin/nheko: /tmp/.mount_nheko-xs2cei//usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /usr/lib64/libQt5QuickWidgets.so.5)
/tmp/.mount_nheko-xs2cei//usr/bin/nheko: /tmp/.mount_nheko-xs2cei//usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /usr/lib64/libQt5Quick.so.5)
/tmp/.mount_nheko-xs2cei//usr/bin/nheko: /tmp/.mount_nheko-xs2cei//usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /usr/lib64/libQt5Qml.so.5)
/tmp/.mount_nheko-xs2cei//usr/bin/nheko: /tmp/.mount_nheko-xs2cei//usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /usr/lib64/libQt5QmlModels.so.5)
```

### Expected behavior

Nheko should start up normally.

### Version

master-8beeba8e

### Operating system

Linux, Other

### Installation method

AppImage

### Qt version

5.15.2

### Desktop Environment

Plasma

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
Does not apply.
```

### Backtrace

```shell
Does not apply.
```

**Comment by deepbluev7** [comment] 2021-11-03 11:12
Duplicate of #735

**Closed** 2021-11-03 11:12 UTC
Labels: bug
