### ISSUE TITLE
Implement an Account Switcher for users with multiple accounts on NHeko

### ISSUE THREAD

**Issue by goliv04053** [Nheko-Reborn/nheko#1278] opened 2023-01-10 23:36 UTC
### The Problem

Switch to other accounts without log out.

### The Solution

Implement an account switcher like Discord account switcher. You don't need to log out to change to another Matrix account.
https://www.xda-developers.com/discord-account-switcher-rolling-out/

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment] 2023-01-18 05:54
Duplicate of #489

**Closed by deepbluev7** 2023-01-18 05:54 UTC
Labels: enhancement
