### ISSUE TITLE
Nheko chrashes when select any channel

### ISSUE THREAD

**Issue by savegame** [Nheko-Reborn/nheko#960] opened 2022-02-23 10:38 UTC
### Describe the bug

**Nheko** works normal lot of time, but today it just crash after some time, when i open any channel.

### To Reproduce

Don't know how to reproduce, its just stop work and it all

### What happened?

1. Open nheko as always
2. select any channel in list
3. channel loads and show messages
4. its crash after few seconds 

### Expected behaviour

just work as always

### Version

0.9.1-b9a4f36 from flatpak

### Operating system

Linux

### Installation method

Flathub

### Desktop Environment

KDE 5.22.5 in  Ubuntu 21.10 ( Pop!_OS)

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
flatpak run io.github.NhekoReborn.Nheko

QIBusPlatformInputContext: invalid portal bus.
[2022-02-23 12:52:19.904] [ui] [info] Restoring window size 946x706
[2022-02-23 12:52:19.964] [ui] [info] WebRTC: initialised GStreamer 1.18.5
[2022-02-23 12:52:21.420] [ui] [info] Loaded jdenticon plugin.
[2022-02-23 12:52:21.844] [ui] [info] starting nheko 0.9.1-b9a4f36
[2022-02-23 12:52:21.947] [db] [info] database ready
[2022-02-23 12:52:21.948] [db] [info] restoring state from cache
[2022-02-23 12:52:21.948] [db] [info] Invalidating self verification status
[2022-02-23 12:52:21.963] [crypto] [info] Could not find inbound megolm session (!_____________:mine.home.matrix.instance, FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, @_____________:matrix.org)
[2022-02-23 12:52:21.968] [crypto] [info] Could not find inbound megolm session (!_____________:matrix.org, FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, @_____________:matrix.org)
[2022-02-23 12:52:21.968] [crypto] [info] Could not find inbound megolm session (!_____________:matrix.org, FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, @_____________:matrix.org)
[2022-02-23 12:52:21.968] [db] [info] Restored 32 rooms from cache
[2022-02-23 12:52:22.063] [crypto] [info] ed25519   : AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
[2022-02-23 12:52:22.063] [crypto] [info] curve25519: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
[2022-02-23 12:52:22.063] [crypto] [info] Online key backup disabled.
[2022-02-23 12:52:22.230] [crypto] [info] Fetched server key count 50 signed_curve25519
[2022-02-23 12:52:22.258] [db] [info] Invalidating self verification status
[2022-02-23 12:52:24.219] [net] [info] TURN server(s) retrieved from homeserver:
[2022-02-23 12:52:24.219] [net] [info] username: @_____________:matrix.org
[2022-02-23 12:52:24.219] [net] [info] ttl: 86400 seconds
[2022-02-23 12:52:24.219] [net] [info] uri: turn:turn.matrix.org:3478?transport=udp
[2022-02-23 12:52:24.219] [net] [info] uri: turn:turn.matrix.org:3478?transport=tcp
[2022-02-23 12:52:24.219] [net] [info] uri: turns:turn.matrix.org:443?transport=tcp
[2022-02-23 12:52:25.870] [qml] [warning] qrc:/qml/delegates/ImageMessage.qml:27:5: QML Image: Blurhash needs size request (qrc:/qml/delegates/ImageMessage.qml:27, )
[2022-02-23 12:52:25.870] [qml] [warning] qrc:/qml/delegates/ImageMessage.qml:27:5: QML Image: Blurhash needs size request (qrc:/qml/delegates/ImageMessage.qml:27, )
[2022-02-23 12:52:25.871] [qml] [warning] qrc:/qml/delegates/ImageMessage.qml:27:5: QML Image: Blurhash needs size request (qrc:/qml/delegates/ImageMessage.qml:27, )
[2022-02-23 12:52:25.871] [qml] [warning] qrc:/qml/delegates/ImageMessage.qml:27:5: QML Image: Blurhash needs size request (qrc:/qml/delegates/ImageMessage.qml:27, )
[2022-02-23 12:52:25.872] [qml] [warning] qrc:/qml/delegates/ImageMessage.qml:27:5: QML Image: Blurhash needs size request (qrc:/qml/delegates/ImageMessage.qml:27, )
terminate called after throwing an instance of 'std::invalid_argument'
  what():  v1.1: invalid version
Error: signal 6:
nheko(+0x46c15f)[0x55f7ea03c15f]
/usr/lib/x86_64-linux-gnu/libc.so.6(+0x39880)[0x7fe105ca8880]
/usr/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x145)[0x7fe105ca87f5]
/usr/lib/x86_64-linux-gnu/libc.so.6(abort+0x127)[0x7fe105c91855]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa67f1)[0x7fe10606c7f1]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb22ec)[0x7fe1060782ec]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb2357)[0x7fe106078357]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb2608)[0x7fe106078608]
nheko(+0x10038a)[0x55f7e9cd038a]
nheko(+0x548b5e)[0x55f7ea118b5e]
nheko(+0x4b272f)[0x55f7ea08272f]
nheko(+0x72a87f)[0x55f7ea2fa87f]
nheko(+0x72aceb)[0x55f7ea2faceb]
nheko(+0x72ae3f)[0x55f7ea2fae3f]
nheko(+0x73397e)[0x55f7ea30397e]
nheko(+0x7344df)[0x55f7ea3044df]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xe0a74)[0x7fe1060a6a74]
/usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x84d2)[0x7fe105e424d2]
/usr/lib/x86_64-linux-gnu/libc.so.6(clone+0x43)[0x7fe105d6d323]
```

### P.S. 
in `### Expected behavior` label in bugreport template you have an missed `u` : `behavior` -> `behaviour`

**Comment by savegame** [comment] 2022-02-23 12:08
When nheko stops working, i was run Schildi Chat, wrote one message... 
Then i try start nheko again, and now it not crash ...

**Comment by deepbluev7** [comment] 2022-02-23 13:49
Duplicate of #957

**Comment by deepbluev7** [comment] 2022-02-23 13:49
(it shouldn't crash after updating the flatpak)

**Closed by deepbluev7** 2022-02-23 13:49 UTC
Labels: bug
