### ISSUE TITLE
Add URL-Preview

### ISSUE THREAD

**Issue by 0verEngineer** [Nheko-Reborn/nheko#1493] opened 2023-06-20 07:14 UTC
### The Problem

Element can load URL-Previews from Synapse if enabled on both sides, i cannot find an option for URL-Preview in Nheko, it would be very nice to have them.

### The Solution

Add URL-Previews like Element.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by tux93** [comment] 2023-10-31 13:03
Duplicate of #561 ?

**Comment by deepbluev7** [comment] 2023-11-01 10:57
Yep, thanks!

**Closed by deepbluev7** 2023-11-01 10:57 UTC
Labels: enhancement
